// MCP server registering practice_* and enrich_* tools. Runs on stdio by
// default (`prepsavant mcp`). Tools call into the Sam HTTP API + the local
// sandbox; responses use MCP sampling for Sam's voice and fall back to the
// server-side voice when sampling is unavailable.
import { createHash } from "node:crypto";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { SamApi } from "./api.js";
import {
  ADAPTER_VERSION,
  readConfig,
  readLocalResearchTargets,
  type LocalResearchTarget,
} from "./config.js";
import {
  runJavascriptSandbox,
  runTypescriptSandbox,
  type SandboxResult,
} from "./sandbox/node.js";
import { runPythonSandbox } from "./sandbox/python.js";
import {
  buildJobEnrichmentGrounding,
  buildJobResearchGrounding,
  buildReviewGrounding,
  inferCompanyPattern,
} from "./persona.js";
import { PersonaCache, DIRECTIVE_FALLBACK } from "./persona-cache.js";
import type { CheckInDirective } from "./api.js";
import { sampleSamVoice, tryExtractJson } from "./sampling.js";

// Surfaces the runner is allowed to push back into the dashboard's enrichment
// cache. Mirrors the server-side TemplateSurface union — kept here as a
// runtime-checkable list so the `forget_dashboard_copy` tool can refuse
// unknown surfaces before round-tripping to the API.
const ENRICHMENT_SURFACES = [
  "kickoff_interview_prep",
  "kickoff_job_search",
  "why_you_fit",
  "application_angle",
  "hint_followup",
  "session_review",
] as const;
type EnrichmentSurface = (typeof ENRICHMENT_SURFACES)[number];

// Best-effort label for the host model. MCP sampling doesn't surface the
// underlying model name, so we mark it as `mcp_host` to make it obvious in
// the dashboard that the copy was generated by whatever host the user has
// (Claude Desktop, Cursor, Codex). The dashboard renders this verbatim
// after "model:".
const RUNNER_MODEL_LABEL = "mcp_host";

function asText(s: string) {
  return { content: [{ type: "text" as const, text: s }] };
}

// Append a machine-readable nextAction JSON block to tool response text.
// Hosts MUST parse and honor the `action` field:
//   - stay_quiet → do nothing proactive
//   - all others → speak `samVoiceLine` verbatim on the next turn
//   - For time_warning/wrap_up only speak once per `timeMilestone` value.
// Returns "" when action is stay_quiet (nothing to append).
function formatDirective(d: CheckInDirective | null | undefined): string {
  if (!d || d.action === "stay_quiet") return "";
  const samVoiceLine = d.samVoiceLine ?? DIRECTIVE_FALLBACK[d.action];
  const payload = {
    action: d.action,
    samVoiceLine,
    reason: d.reason,
    ...(d.timeMilestone !== undefined && d.timeMilestone !== null
      ? { timeMilestone: d.timeMilestone }
      : {}),
  };
  return `\nnextAction: ${JSON.stringify(payload)}`;
}

function summariseSandbox(r: SandboxResult): string {
  const passed = r.cases.filter((c) => c.passed).length;
  const failed = r.cases.length - passed;
  return `${r.outcome.toUpperCase()} • ${passed} passed, ${failed} failed • ${r.runtimeVersion} • ${r.durationMs}ms`;
}

export async function runMcpServer(): Promise<void> {
  const cfg = readConfig();
  if (!cfg.token) {
    // We still start the server so the host can introspect tools, but every
    // tool call surfaces a clear error pointing at `prepsavant auth`.
    process.stderr.write(
      "[prepsavant] No device token. Run `prepsavant auth` to authorize.\n",
    );
  }
  const api = new SamApi(cfg);
  const persona = new PersonaCache(api);
  // Best-effort warmup so the first tool call already has the live persona
  // composed from the server. Failure here is non-fatal; PersonaCache will
  // serve the bundled fallback prompt and retry on demand.
  if (cfg.token) {
    persona.refresh(true).catch(() => {
      // Already logged inside PersonaCache.refresh.
    });
  }

  // Helper: every Sam-voice sampling pass goes through here so all tools
  // share the same up-to-date system prompt without each one having to
  // remember to re-poll.
  const samplingSystemPrompt = async (): Promise<string> => {
    const resolved = await persona.refresh();
    return resolved.systemPrompt;
  };

  // Best-effort enrichment push. Failures are surfaced on stderr but never
  // bubble into the user-visible tool response — the runner has already done
  // its primary job (returning the generated text); the dashboard cache is a
  // nice-to-have copy. Expected 4xx responses (402 missing entitlement, 400
  // bad request from a stale surface enum) are logged at "warn" so a
  // free-tier user — or a runner that ships ahead of a server schema bump —
  // doesn't see a noisy stack trace on every coaching turn.
  const pushEnrichmentBestEffort = async (args: {
    surface: EnrichmentSurface;
    subject?: string;
    body: string;
  }): Promise<void> => {
    if (!args.body.trim()) return;
    try {
      await api.putSamEnrichment({
        surface: args.surface,
        subject: args.subject,
        body: args.body,
        modelLabel: RUNNER_MODEL_LABEL,
      });
    } catch (err) {
      const e = err as { status?: number; message?: string };
      const isExpected4xx =
        typeof e.status === "number" && e.status >= 400 && e.status < 500;
      const tag = isExpected4xx ? "warn" : "error";
      process.stderr.write(
        `[prepsavant] ${tag}: enrichment push (${args.surface}${args.subject ? `:${args.subject}` : ""}) failed: ${e.message ?? err}\n`,
      );
    }
  };

  const server = new McpServer(
    { name: "sam", version: ADAPTER_VERSION },
    { capabilities: { tools: {} } },
  );

  // ---------------------------------------------------------------------
  // practice_list_questions
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_list_questions",
    {
      description: "List interview-prep questions available for practice.",
      inputSchema: {},
    },
    async () => {
      const list = await api.listQuestions();
      const lines = list.items.map(
        (q) =>
          `${q.id}\t${q.title} [${q.roleFamily}/${q.difficulty}] (${q.languages.join(", ")})`,
      );
      return asText(lines.join("\n") || "No questions available.");
    },
  );

  // ---------------------------------------------------------------------
  // practice_start_session
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_start_session",
    {
      description:
        "Start a new practice session for a given question. Returns the session id and the kickoff brief (which contains HOST INSTRUCTIONS for proactive cadence). Optionally pass targetDurationMinutes to enable timed-session directives.",
      inputSchema: {
        questionId: z.string(),
        companyId: z.string().optional(),
        targetDurationMinutes: z.number().int().min(5).max(180).optional(),
      },
    },
    async (args) => {
      const start = await api.startSession({
        questionId: args.questionId,
        companyId: args.companyId,
        targetDurationMinutes: args.targetDurationMinutes,
      });
      const detail = (await api.getSession(start.sessionId)) as {
        kickoffBriefVerbatim?: string;
      };
      return asText(
        [
          `session_id: ${start.sessionId}`,
          "",
          detail.kickoffBriefVerbatim ?? "(no kickoff brief)",
        ].join("\n"),
      );
    },
  );

  // ---------------------------------------------------------------------
  // practice_submit_attempt — runs the user's code in the local sandbox,
  // pushes the graded attempt, asks the host model for Sam-voice review.
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_submit_attempt",
    {
      description:
        "Run the user's solution against the pinned tests in a local sandbox, push the graded attempt to Sam, and produce a Sam-voice review.",
      inputSchema: {
        sessionId: z.string(),
        language: z.enum(["python", "javascript", "typescript"]),
        code: z.string().min(1),
      },
    },
    async (args) => {
      // 1. Fetch the question + pinned tests for this session.
      const session = (await api.getSession(args.sessionId)) as {
        session: { questionId: string; companyName?: string };
        question: { title: string };
        attempts: { id: string; attemptNumber: number }[];
        hints: { level: number }[];
      };
      const question = await api.getQuestion(session.session.questionId);
      const tests = question.tests[args.language];
      if (!tests) {
        return asText(
          `No pinned tests for language "${args.language}" on this question.`,
        );
      }
      const timeoutMs = tests.timeoutMs ?? 5_000;

      // 2. Run sandbox.
      const sandbox =
        args.language === "python"
          ? runPythonSandbox(args.code, tests.entry, tests.cases, timeoutMs)
          : args.language === "typescript"
            ? runTypescriptSandbox(args.code, tests.entry, tests.cases, timeoutMs)
            : runJavascriptSandbox(args.code, tests.entry, tests.cases, timeoutMs);

      const passed = sandbox.cases.filter((c) => c.passed).length;
      const failed = sandbox.cases.length - passed;

      // 3. Push attempt.
      const pushed = await api.pushAttempt(args.sessionId, {
        language: args.language,
        code: args.code,
        outcome: sandbox.outcome,
        timedOut: sandbox.timedOut,
        durationMs: sandbox.durationMs,
        adapterVersion: ADAPTER_VERSION,
        runtimeVersion: sandbox.runtimeVersion,
        cases: sandbox.cases.map((c) => ({
          id: c.id,
          // Server's RunnerPushAttemptBody requires a `status` enum, not a
          // boolean. We coarsen booleans to "pass" / "fail" — sandbox runners
          // surface timeouts via the top-level `outcome`/`timedOut` already.
          status: c.passed ? ("pass" as const) : ("fail" as const),
          durationMs: c.durationMs,
          stderrExcerpt: c.stderrExcerpt,
        })),
      });

      // 4. Ask the host model for review/probe in Sam's voice.
      // Infer company pattern from the company name so Sam frames feedback
      // against what this company actually tests, not a generic root cause.
      const companyPattern = session.session.companyName
        ? inferCompanyPattern(session.session.companyName)
        : "generic";
      const grounding = buildReviewGrounding({
        questionTitle: question.question.title,
        language: args.language,
        outcome: sandbox.outcome,
        passedCount: passed,
        failedCount: failed,
        failedCases: sandbox.cases
          .filter((c) => !c.passed)
          .map((c) => ({ id: c.id, stderrExcerpt: c.stderrExcerpt })),
        attemptNumber: (session.attempts[session.attempts.length - 1]?.attemptNumber ?? 0) + 1,
        hintsTaken: session.hints.length,
        companyPattern,
      });
      const fallbackText = `${pushed.reviewVerbatim}\n\n${pushed.probeVerbatim}`;
      const sampling = await sampleSamVoice(
        server.server,
        await samplingSystemPrompt(),
        grounding,
        fallbackText,
      );

      let reviewText = pushed.reviewVerbatim;
      let probeText: string | undefined = pushed.probeVerbatim;
      let source: "runner_sampling" | "runner_fallback" = "runner_fallback";
      if (sampling.source === "runner_sampling") {
        const parsed = tryExtractJson<{ review?: string; probe?: string }>(
          sampling.text,
        );
        if (parsed?.review) {
          reviewText = parsed.review;
          probeText = parsed.probe;
          source = "runner_sampling";
        } else {
          reviewText = sampling.text;
          source = "runner_sampling";
        }
      }

      // 5. Push the final review back so the dashboard can render it.
      try {
        await api.pushReview(args.sessionId, {
          attemptId: pushed.attempt.id,
          reviewText,
          probeText,
          source,
        });
      } catch {
        // Non-fatal: the attempt is already saved with the server-side fallback.
      }

      // 6. Mirror the same review into the new surface×subject enrichment
      //    cache so the session-review surface on the dashboard renders the
      //    "Generated locally by Sam in your IDE" badge instead of the
      //    static template fallback. We only push when sampling actually
      //    succeeded — the server-side fallback is identical to what the
      //    template would render anyway.
      if (source === "runner_sampling") {
        const composed = probeText
          ? `${reviewText}\n\n${probeText}`
          : reviewText;
        await pushEnrichmentBestEffort({
          surface: "session_review",
          subject: args.sessionId,
          body: composed,
        });
      }

      return asText(
        [
          summariseSandbox(sandbox),
          "",
          reviewText,
          probeText ? `\n${probeText}` : "",
          formatDirective(pushed.nextAction),
        ]
          .filter(Boolean)
          .join("\n"),
      );
    },
  );

  // ---------------------------------------------------------------------
  // practice_request_hint
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_request_hint",
    {
      description: "Ask Sam for the next hint on the active session.",
      inputSchema: { sessionId: z.string() },
    },
    async (args) => {
      const hint = await api.requestHint(args.sessionId);
      const hintLine = hint.exhausted
        ? `(no more hints — level ${hint.totalLevels} reached)`
        : `Hint ${hint.level}/${hint.totalLevels}:\n${hint.hintText}`;
      const directive = formatDirective(hint.nextAction);
      return asText(directive ? `${hintLine}${directive}` : hintLine);
    },
  );

  // ---------------------------------------------------------------------
  // practice_check_in — host calls this after every message during a
  // session (or on a ~3 min timer) to get the current directive. The
  // host MUST speak samVoiceLine verbatim when action !== stay_quiet.
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_check_in",
    {
      description:
        "Check in with Sam during an active practice session. Returns a directive: stay_quiet (do nothing), probe (surface the samVoiceLine to the user verbatim), hint_offer (tell the user a hint is available), time_warning, or wrap_up. Call this after every user message during a session, or on a ~3 min heartbeat. The host MUST speak samVoiceLine verbatim when action is not stay_quiet.",
      inputSchema: { sessionId: z.string() },
    },
    async (args) => {
      const directive = await api.checkIn(args.sessionId);
      // Always return the full directive verbatim as JSON — strict pass-through
      // so hosts have a stable, typed contract regardless of action.
      // When action=stay_quiet the host must do nothing proactive.
      // samVoiceLine is passed as-is from the server; hosts may fall back to
      // their own phrasing if null, but the runner does not substitute here.
      const samVoiceLine = directive.samVoiceLine ?? null;
      const payload: Record<string, unknown> = {
        action: directive.action,
        samVoiceLine,
        reason: directive.reason,
      };
      if ("timeMilestone" in directive && directive.timeMilestone != null) {
        payload["timeMilestone"] = directive.timeMilestone;
      }
      return asText(JSON.stringify(payload));
    },
  );

  // ---------------------------------------------------------------------
  // practice_end_session
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_end_session",
    {
      description: "End the active practice session.",
      inputSchema: { sessionId: z.string() },
    },
    async (args) => {
      await api.endSession(args.sessionId);
      return asText("Session ended.");
    },
  );

  // ---------------------------------------------------------------------
  // enrich_job — push why-fit + application-angle for a job.
  // ---------------------------------------------------------------------
  server.registerTool(
    "enrich_job",
    {
      description:
        "Generate Sam-voice why-fit and application-angle text for a job and push them back to the Sam dashboard. Pass calibration fields when available — they let Sam apply the Search spec's 5-dimension fit-score reasoning and name concrete risks.",
      inputSchema: {
        jobId: z.string(),
        jobTitle: z.string(),
        company: z.string(),
        jobDescription: z.string().optional(),
        candidateProfileSummary: z.string(),
        // Structured calibration fields from the candidate's profile.
        // All optional: Sam degrades gracefully when they are absent.
        currentProofPoints: z.array(z.string()).optional(),
        weakSpots: z.array(z.string()).optional(),
        calibratedTargetIndustries: z.array(z.string()).optional(),
        compFloor: z.number().optional(),
        sponsorshipNeed: z.boolean().optional(),
        geoPreference: z.string().optional(),
      },
    },
    async (args) => {
      const grounding = buildJobEnrichmentGrounding({
        jobTitle: args.jobTitle,
        company: args.company,
        jobDescription: args.jobDescription,
        candidateProfileSummary: args.candidateProfileSummary,
        currentProofPoints: args.currentProofPoints,
        weakSpots: args.weakSpots,
        calibratedTargetIndustries: args.calibratedTargetIndustries,
        compFloor: args.compFloor,
        sponsorshipNeed: args.sponsorshipNeed,
        geoPreference: args.geoPreference,
      });
      const sampling = await sampleSamVoice(
        server.server,
        await samplingSystemPrompt(),
        grounding,
        "",
      );
      let whyYouFit = "";
      let applicationAngle = "";
      let risks: string[] = [];
      let firstActionAngle = "";
      let source: "runner_sampling" | "runner_fallback" = "runner_fallback";
      if (sampling.source === "runner_sampling") {
        const parsed = tryExtractJson<{
          why_you_fit?: string;
          application_angle?: string;
          risks?: string[];
          first_action_angle?: string;
        }>(sampling.text);
        whyYouFit = parsed?.why_you_fit ?? sampling.text;
        applicationAngle = parsed?.application_angle ?? "";
        risks = parsed?.risks ?? [];
        firstActionAngle = parsed?.first_action_angle ?? "";
        source = "runner_sampling";
      }
      if (!whyYouFit) {
        return asText(
          "Sam could not generate enrichment locally (host refused sampling and no fallback was provided). Try again from the dashboard.",
        );
      }
      try {
        await api.pushJobEnrichment(args.jobId, {
          whyYouFit,
          applicationAngle,
          source,
        });
      } catch (err) {
        return asText(`Generated text but could not push it: ${(err as Error).message}`);
      }
      // Mirror into the new surface×subject enrichment cache so the
      // dashboard's why-you-fit / application-angle cards flip to the
      // "Generated locally by Sam in your IDE" state. Keep this best-effort
      // — if the user is on a free tier we still want the legacy
      // pushJobEnrichment above to record the result.
      await pushEnrichmentBestEffort({
        surface: "why_you_fit",
        subject: args.jobId,
        body: whyYouFit,
      });
      if (applicationAngle.trim()) {
        await pushEnrichmentBestEffort({
          surface: "application_angle",
          subject: args.jobId,
          body: applicationAngle,
        });
      }
      const outputParts = ["why_you_fit:", whyYouFit, "", "application_angle:", applicationAngle];
      if (firstActionAngle.trim()) {
        outputParts.push("", "first_action:", firstActionAngle);
      }
      if (risks.length > 0) {
        outputParts.push("", "risks:", ...risks.map((r) => `- ${r}`));
      }
      return asText(
        outputParts.join("\n"),
      );
    },
  );

  // ---------------------------------------------------------------------
  // enrich_shortlist — push a one-line annotation onto a shortlist item.
  // ---------------------------------------------------------------------
  server.registerTool(
    "enrich_shortlist",
    {
      description: "Push a Sam-voice annotation onto a shortlist item.",
      inputSchema: {
        shortlistItemId: z.string(),
        prompt: z.string(),
      },
    },
    async (args) => {
      const sampling = await sampleSamVoice(
        server.server,
        await samplingSystemPrompt(),
        args.prompt,
        "",
      );
      if (!sampling.text) {
        return asText("Host refused sampling and no fallback was supplied.");
      }
      try {
        await api.pushShortlistAnnotation(args.shortlistItemId, {
          annotation: sampling.text,
          source: sampling.source,
        });
      } catch (err) {
        return asText(`Generated text but could not push it: ${(err as Error).message}`);
      }
      return asText(sampling.text);
    },
  );

  // ---------------------------------------------------------------------
  // forget_dashboard_copy — clear a previously pushed enrichment row so the
  // dashboard stops showing the locally generated copy and falls back to the
  // server-side template. Useful when the user says "Sam, forget what you
  // said about job X" or when a job's underlying posting changes and the
  // generated copy is no longer accurate.
  // ---------------------------------------------------------------------
  server.registerTool(
    "forget_dashboard_copy",
    {
      description:
        "Forget a previously pushed Sam enrichment for a given surface (and optional subject id) so the dashboard reverts to the template fallback.",
      inputSchema: {
        surface: z.enum(ENRICHMENT_SURFACES),
        subject: z.string().optional(),
      },
    },
    async (args) => {
      // The server's DELETE /sam/enrichment is idempotent — it returns
      // { ok: true } whether or not a matching row existed — so we don't try
      // to distinguish "deleted" from "nothing to delete" in the response.
      try {
        await api.deleteSamEnrichment({
          surface: args.surface,
          subject: args.subject,
        });
        return asText(
          `Forgot ${args.surface}${args.subject ? `:${args.subject}` : ""}.`,
        );
      } catch (err) {
        return asText(
          `Could not forget ${args.surface}: ${(err as Error).message}`,
        );
      }
    },
  );

  // ---------------------------------------------------------------------
  // research_jobs — scan configured target companies' careers pages and
  // push the extracted openings back into the Sam dashboard so they stop
  // appearing as "sample" jobs.
  // ---------------------------------------------------------------------
  server.registerTool(
    "research_jobs",
    {
      description:
        "Scan configured target companies' careers pages and push the openings back to the Sam dashboard. Newly recorded jobs appear in shortlists without the Sample badge. When `targets` is omitted the runner falls back to the local file ~/.prepsavant/research-targets.json and then to the user's saved list on the dashboard. Re-fetched pages whose content hash matches the previous run within the freshness window are skipped to save host-model tokens; pass `force: true` to bypass the cache.",
      inputSchema: {
        targets: z
          .array(
            z.object({
              companyName: z.string(),
              careersUrl: z.string().url(),
              companySlug: z.string().optional(),
              industry: z.string().optional(),
            }),
          )
          .min(1)
          .optional(),
        maxJobsPerCompany: z.number().int().min(1).max(50).optional(),
        notes: z.string().optional(),
        // Bypass the careers-page content-hash cache and force a fresh
        // model extraction for every target.
        force: z.boolean().optional(),
        // Override the default freshness window (in hours). When the
        // cached fetch is younger than this and the hash matches, the
        // model call is skipped. Defaults to 6h.
        cacheTtlHours: z.number().int().min(0).max(168).optional(),
      },
    },
    async (args) => {
      const maxJobs = args.maxJobsPerCompany ?? 20;
      const force = args.force === true;
      const cacheTtlMs = (args.cacheTtlHours ?? 6) * 60 * 60 * 1000;
      const summary: string[] = [];

      // Resolve target list. Order:
      //   1. Explicit `targets` argument (one-off scan).
      //   2. ~/.prepsavant/research-targets.json (per-machine override).
      //   3. GET /api/jobs/research/targets (saved on the dashboard).
      // We expose where the list came from in the summary so users
      // understand why a "no targets argument" call still scanned 5 sites.
      let targets: LocalResearchTarget[] = [];
      let source: "argument" | "local_file" | "saved" = "argument";
      if (args.targets && args.targets.length > 0) {
        targets = args.targets.map((t) => ({
          companyName: t.companyName,
          careersUrl: t.careersUrl,
          companySlug: t.companySlug,
          industry: t.industry,
        }));
        source = "argument";
      } else {
        const local = readLocalResearchTargets();
        if (local && local.length > 0) {
          targets = local;
          source = "local_file";
        } else {
          try {
            const saved = await api.listResearchTargets();
            targets = saved.targets.map((t) => ({
              companyName: t.companyName,
              careersUrl: t.careersUrl,
              companySlug: t.slug,
              industry: t.industry,
            }));
            source = "saved";
          } catch (err) {
            return asText(
              `No targets supplied and could not load saved targets: ${(err as Error).message}`,
            );
          }
        }
      }

      if (targets.length === 0) {
        return asText(
          'No targets to scan. Pass `targets: [{ companyName, careersUrl }, ...]`, drop a JSON file at ~/.prepsavant/research-targets.json, or save a list at /dashboard/job-search/targets.',
        );
      }

      let run: Awaited<ReturnType<typeof api.startResearchRun>>;
      try {
        run = await api.startResearchRun({
          runnerVersion: ADAPTER_VERSION,
          modelHint: "host_sampling",
          notes: args.notes,
        });
      } catch (err) {
        return asText(
          `Could not open a research run: ${(err as Error).message}`,
        );
      }
      summary.push(`run_id: ${run.id}`);
      summary.push(`targets_source: ${source} (${targets.length} companies)`);

      let totalAdded = 0;
      let totalUpdated = 0;
      let totalSkipped = 0;
      let totalUnchanged = 0;
      let companiesAttempted = 0;
      let companiesSucceeded = 0;
      const errors: string[] = [];

      for (let i = 0; i < targets.length; i++) {
        const target = targets[i]!;
        const isLast = i === targets.length - 1;
        companiesAttempted += 1;
        // Every record call carries an explicit `company` descriptor so
        // /admin/research can show a per-company outcome row even when the
        // jobs[] payload is empty (refusal / fetch-error path).
        const companyDescriptor = {
          name: target.companyName,
          slug: target.companySlug,
          careersUrl: target.careersUrl,
        };
        // Build the per-iteration record body so error/refusal branches still
        // count this company toward `companiesScanned` on the server side
        // (the API counts unique slugs in the `jobs[]` it sees). When the
        // body is empty we can't bump that counter, so we fall back to
        // surfacing the attempt via `errorText` instead.
        let recordBody: Parameters<typeof api.recordResearchResult>[1] = {
          jobs: [],
          company: companyDescriptor,
          complete: isLast,
        };
        let outcomeLine = "";
        let errorLine: string | null = null;

        try {
          const page = await fetchCareersPage(target.careersUrl);
          const contentHash = sha256Hex(page);

          // Cache short-circuit: when the freshly-hashed page matches the
          // last successful extract for this (owner, careersUrl) AND the
          // cached fetch is still inside the freshness window, we skip the
          // host-model call entirely. The server-side accounting bumps a
          // dedicated `companiesUnchanged` counter so /admin/research can
          // tell this apart from real fetch/sampling errors.
          let cacheHit = false;
          if (!force) {
            try {
              const cached = await api.getResearchCache(target.careersUrl);
              if (
                cached &&
                cached.contentHash === contentHash &&
                Date.now() - new Date(cached.fetchedAt).getTime() < cacheTtlMs
              ) {
                cacheHit = true;
              }
            } catch {
              // Cache lookup failures are non-fatal; fall through to a
              // normal extraction. The server will recover next time.
            }
          }

          if (cacheHit) {
            recordBody = {
              jobs: [],
              company: companyDescriptor,
              complete: isLast,
              careersUrl: target.careersUrl,
              companyName: target.companyName,
              contentHash,
              skipReason: "unchanged",
            };
            outcomeLine = `${target.companyName}: unchanged since last run — skipped model call`;
          } else {
            const grounding = buildJobResearchGrounding({
              companyName: target.companyName,
              careersUrl: target.careersUrl,
              pageExcerpt: page,
              maxJobs,
            });
            const sampling = await sampleSamVoice(
              server.server,
              SAM_RESEARCH_SYSTEM_PROMPT,
              grounding,
              "",
            );

            if (sampling.source !== "runner_sampling" || !sampling.text) {
              errorLine = `${target.companyName}: host refused sampling — skipped.`;
              recordBody = {
                jobs: [],
                company: companyDescriptor,
                complete: isLast,
                careersUrl: target.careersUrl,
                companyName: target.companyName,
                skipReason: "error",
                errorText: `host_refused_sampling: ${target.companyName}`,
              };
            } else {
              const parsed = tryExtractJson<{ jobs?: unknown[] }>(sampling.text);
              const rawJobs = Array.isArray(parsed?.jobs) ? parsed!.jobs : [];
              const jobs = rawJobs
                .map((j) =>
                  normalizeExtractedJob(j, target, target.careersUrl, maxJobs),
                )
                .filter(
                  (j): j is NonNullable<ReturnType<typeof normalizeExtractedJob>> =>
                    j !== null,
                )
                .slice(0, maxJobs);
              recordBody = {
                jobs,
                company: companyDescriptor,
                complete: isLast,
                careersUrl: target.careersUrl,
                companyName: target.companyName,
                contentHash,
              };
            }
          }
        } catch (err) {
          errorLine = `${target.companyName}: ${(err as Error).message}`;
          recordBody = {
            jobs: [],
            company: companyDescriptor,
            complete: isLast,
            careersUrl: target.careersUrl,
            companyName: target.companyName,
            skipReason: "error",
            errorText: `${target.companyName}: ${(err as Error).message}`,
          };
        }

        // Always record the per-company outcome so the run's accounting and
        // completion flag stay consistent, even on refusal/fetch failure.
        let recordSucceeded = false;
        try {
          const recorded = await api.recordResearchResult(run.id, recordBody);
          recordSucceeded = true;
          totalAdded += recorded.added;
          totalUpdated += recorded.updated;
          totalSkipped += recorded.skipped;
          if (recordBody.skipReason === "unchanged") {
            totalUnchanged += 1;
            companiesSucceeded += 1;
            // outcomeLine already set above; nothing to overwrite.
          } else if (errorLine === null) {
            companiesSucceeded += 1;
            outcomeLine = `${target.companyName}: +${recorded.added} new, ~${recorded.updated} updated, ${recorded.skipped} skipped`;
          }
        } catch (recordErr) {
          errorLine =
            errorLine ??
            `${target.companyName}: record failed — ${(recordErr as Error).message}`;
        }

        // Best-effort finalize: if the LAST per-company record call failed,
        // the run is left in-flight on the server. Send one explicit empty
        // close so the run flips to completed/error and doesn't show as
        // "in-flight forever" in /admin/research.
        if (isLast && !recordSucceeded) {
          try {
            await api.recordResearchResult(run.id, {
              jobs: [],
              company: companyDescriptor,
              complete: true,
              errorText: errorLine ?? "finalize_after_record_failure",
            });
          } catch {
            // Surface via summary; nothing more we can do from the runner.
          }
        }

        if (errorLine) errors.push(errorLine);
        if (outcomeLine) summary.push(outcomeLine);
      }

      summary.push("");
      const unchangedSummary =
        totalUnchanged > 0 ? `, ${totalUnchanged} unchanged (cached)` : "";
      summary.push(
        `Totals: ${totalAdded} added, ${totalUpdated} updated, ${totalSkipped} skipped${unchangedSummary} across ${companiesSucceeded}/${companiesAttempted} companies.`,
      );
      if (errors.length > 0) {
        summary.push("");
        summary.push("Issues:");
        for (const e of errors) summary.push(`  - ${e}`);
      }
      return asText(summary.join("\n"));
    },
  );

  await server.connect(new StdioServerTransport());
  process.stderr.write(
    `[prepsavant] sam MCP server v${ADAPTER_VERSION} listening on stdio\n`,
  );
}

// Targeted system prompt for the research extractor. We deliberately do NOT
// reuse SAM_SYSTEM_PROMPT here — Sam's coaching voice is for users, not for a
// JSON extraction task. This keeps the model focused and the output parseable.
const SAM_RESEARCH_SYSTEM_PROMPT = `You are a careful HTML-to-JSON extractor for a job-search assistant. Your only
job is to identify open engineering / technical roles on a careers page excerpt
and return them as strict JSON. Never invent roles that are not on the page.
Never include sales, marketing, finance, recruiting, or general operations
roles. If you are uncertain, omit the role. Output JSON only — no commentary,
no markdown fences.`;

const ROLE_FAMILIES = new Set([
  "backend",
  "frontend",
  "fullstack",
  "data",
  "infra",
  "mobile",
  "ml",
  "security",
  "other",
]);

const SENIORITIES = new Set([
  "intern",
  "junior",
  "mid",
  "senior",
  "staff",
  "principal",
  "lead",
  "manager",
]);

const REMOTE_POLICIES = new Set(["remote", "hybrid", "onsite", "unspecified"]);

interface ResearchTarget {
  companyName: string;
  careersUrl: string;
  companySlug?: string;
  industry?: string;
}

interface NormalizedJob {
  companyName: string;
  companySlug?: string;
  industry?: string;
  careersUrl?: string;
  title: string;
  canonicalUrl: string;
  source: string;
  roleFamily: string;
  seniority: string;
  location: string;
  remotePolicy: string;
  postingExcerpt: string;
  team?: string;
}

function pickEnum(
  value: unknown,
  allowed: Set<string>,
  fallback: string,
): string {
  if (typeof value !== "string") return fallback;
  const v = value.trim().toLowerCase();
  return allowed.has(v) ? v : fallback;
}

function asString(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const t = value.trim();
  return t ? t : undefined;
}

function absolutize(url: string | undefined, base: string): string | null {
  if (!url) return null;
  try {
    return new URL(url, base).toString();
  } catch {
    return null;
  }
}

function normalizeExtractedJob(
  raw: unknown,
  target: ResearchTarget,
  baseUrl: string,
  _maxJobs: number,
): NormalizedJob | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  const title = asString(r["title"]);
  if (!title) return null;
  const canonicalUrl =
    absolutize(asString(r["canonicalUrl"]) ?? asString(r["url"]), baseUrl) ??
    target.careersUrl;
  return {
    companyName: target.companyName,
    companySlug: target.companySlug,
    industry: target.industry,
    careersUrl: target.careersUrl,
    title,
    canonicalUrl,
    source: "runner",
    roleFamily: pickEnum(r["roleFamily"], ROLE_FAMILIES, "other"),
    seniority: pickEnum(r["seniority"], SENIORITIES, "mid"),
    location: asString(r["location"]) ?? "Unspecified",
    remotePolicy: pickEnum(r["remotePolicy"], REMOTE_POLICIES, "unspecified"),
    postingExcerpt:
      asString(r["postingExcerpt"]) ??
      asString(r["summary"]) ??
      `Open role at ${target.companyName}.`,
    team: asString(r["team"]),
  };
}

// Minimal, dependency-free careers-page fetch + HTML→text. Keeps the runner
// package self-contained (no jsdom / cheerio). Trims to a budget so the host
// model sees a focused excerpt rather than a huge nav/footer dump.
async function fetchCareersPage(url: string): Promise<string> {
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(), 15_000);
  try {
    const res = await fetch(url, {
      headers: {
        "user-agent": `prepsavant-runner/${ADAPTER_VERSION} (+https://prepsavant.com)`,
        accept: "text/html,application/xhtml+xml",
      },
      signal: ac.signal,
      redirect: "follow",
    });
    if (!res.ok) {
      throw new Error(`careers page returned HTTP ${res.status}`);
    }
    const html = await res.text();
    return htmlToText(html).slice(0, 12_000);
  } finally {
    clearTimeout(timer);
  }
}

// SHA-256 hex digest used as the careers-page cache key. We hash the
// already-trimmed text (not the raw HTML) so cosmetic markup churn —
// CSRF tokens, cache-busting query strings in scripts, etc. — does not
// invalidate the cache when the visible role list is identical.
function sha256Hex(input: string): string {
  return createHash("sha256").update(input).digest("hex");
}

function htmlToText(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, " ")
    .replace(/<\/(p|div|li|h[1-6]|tr|br)>/gi, "\n")
    .replace(/<br\s*\/?\s*>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&#39;/gi, "'")
    .replace(/&quot;/gi, '"')
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}
