// MCP server registering coached_*, ai_assisted_*, and enrich_* tools. Runs on stdio
// by default (`prepsavant mcp`). Tools call into the Sam HTTP API + the local
// sandbox; responses use MCP sampling for Sam's voice and fall back to the
// server-side voice when sampling is unavailable. The legacy `practice_*` tool
// aliases were removed in 0.5.0 — see the §coached.tool-aliases section in
// `artifacts/sam/CONTRACTS.md` for the migration mapping.
import { createHash } from "node:crypto";
import { McpServer, type RegisteredTool } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import type { Transport } from "@modelcontextprotocol/sdk/shared/transport.js";
import { z } from "zod";
import { SamApi } from "./api.js";
import {
  ADAPTER_VERSION,
  readConfig,
  readLocalResearchTargets,
  type LocalResearchTarget,
} from "./config.js";
import {
  buildJobEnrichmentGrounding,
  buildJobResearchGrounding,
} from "./persona.js";
import { PersonaCache } from "./persona-cache.js";
import { sampleSamVoice, tryExtractJson } from "./sampling.js";
import { acquireRunnerLock } from "./runner-lock.js";
import {
  startCoachedSession,
  getCoachedSession,
  endCoachedSession,
  recordAiAssist,
  updateHintLevel,
} from "./coached/session.js";
import { bootCoachedCadenceLoop } from "./coached/cadence-boot.js";
import {
  buildCheckInPayload,
  buildCheckInPayloadFromResolved,
  isStallEscalation,
  resolveCoachedWorkDir,
  resolveCheckInDirective,
  shouldRefreshProgressForStall,
  escalateForStall,
} from "./coached/check-in.js";
import {
  computeProgressSignals,
  type AttemptForSignals,
} from "./coached/progress-signals.js";
import {
  BUNDLED_NUDGE_INSTRUCTION,
  enrichDirectiveWithDiff,
} from "./coached/diff-aware-nudge.js";
import {
  buildCoachedPostMortemText,
  formatCoachedEndSessionResponse,
  rewriteSessionMemoryWithDeps,
} from "./coached/post-mortem.js";
import { ApiError } from "./api.js";
// Task #1061 — AI-Assisted MCP tool family. The MCP host (Claude Desktop,
// Cursor, Codex, etc.) IS the AI assistant in AI-Assisted mode, so the
// tools are deliberately thin wrappers over the existing /runner/ai-sessions
// API plus an opaque session-id handle. In-process Cursor hooks +
// the per-event signing log were retired in @prepsavant/mcp@2.0.0
// (Task #1193); end-of-session evidence now flows through the
// Cursor-export upload path (`prepsavant upload-cursor-export`).
import { generateEphemeralKeyPair, sha256Hex as aiSha256Hex } from "./ai-assisted/signing.js";
// Task #1064 — verbatim relay protocol helpers + best-effort IDE rule install.
import { wrapSamVerbatim } from "./sam-verbatim.js";
import {
  installAiAssistedIdeRulesBestEffort,
  installIdeRulesBestEffort,
} from "./skills/installer.js";
// Task #1399 — shared CLI UI helpers for the polished AI-Assisted
// startup banner returned by `ai_assisted_start_session`.
import { makeColors } from "./cli-ui/index.js";
import { renderAiAssistedStartupBanner } from "./cli-ui/ai-assisted-banner.js";

// Surfaces the runner is allowed to push back into the dashboard's enrichment
// cache. Mirrors the server-side TemplateSurface union — kept here as a
// runtime-checkable list so the `forget_dashboard_copy` tool can refuse
// unknown surfaces before round-tripping to the API.
const ENRICHMENT_SURFACES = [
  "kickoff_interview_prep",
  "kickoff_job_search",
  "why_you_fit",
  "application_angle",
  "hint_followup",
  "session_review",
] as const;
type EnrichmentSurface = (typeof ENRICHMENT_SURFACES)[number];

// Best-effort label for the host model. MCP sampling doesn't surface the
// underlying model name, so we mark it as `mcp_host` to make it obvious in
// the dashboard that the copy was generated by whatever host the user has
// (Claude Desktop, Cursor, Codex). The dashboard renders this verbatim
// after "model:".
const RUNNER_MODEL_LABEL = "mcp_host";

function asText(s: string) {
  return { content: [{ type: "text" as const, text: s }] };
}

// Task #800 / #804 — best-effort end-of-session memory rewrite.
//
// Wires the runtime `SamApi` + MCP `Server` to the pure
// `rewriteSessionMemoryWithDeps` helper in `coached/post-mortem.ts`.
// All failure-mode behavior (host refusal, oversize, 413, generic
// errors) lives in the helper and is unit-tested there. This wrapper
// only handles the things that need live runtime objects: fetching the
// candidate profile (404 → no-op so a brand-new candidate doesn't
// trigger a rewrite), and translating between the helper's
// `{sample, patch}` deps and `sampleSamVoice` / `SamApi.updateSessionMemory`.
async function rewriteSessionMemoryBestEffort(deps: {
  api: SamApi;
  server: import("@modelcontextprotocol/sdk/server/index.js").Server;
  questionTitle: string;
  attemptsTotal: number;
  hintsUsed: number;
  passedLatest: boolean | undefined;
  aiAssistDetected: boolean;
}): Promise<void> {
  let priorMemory = "";
  try {
    const profile = await deps.api.getCandidateProfile();
    if (!profile) return;
    priorMemory = profile.sessionMemory ?? "";
  } catch (err) {
    process.stderr.write(
      `[coached_end_session] session memory rewrite skipped: getCandidateProfile failed (${err instanceof Error ? err.message : String(err)})\n`,
    );
    return;
  }

  await rewriteSessionMemoryWithDeps(
    {
      priorMemory,
      questionTitle: deps.questionTitle,
      attemptsTotal: deps.attemptsTotal,
      hintsUsed: deps.hintsUsed,
      passedLatest: deps.passedLatest,
      aiAssistDetected: deps.aiAssistDetected,
    },
    {
      sample: ({ systemPrompt, userPrompt }) =>
        sampleSamVoice(deps.server, systemPrompt, userPrompt, priorMemory),
      patch: (sessionMemory) =>
        deps.api.updateSessionMemory({ sessionMemory }),
    },
  );
}

// Task #1149 — `runMcpServer` accepts optional dependency overrides so an
// in-memory MCP client can drive the server end-to-end (stub `SamApi` +
// `InMemoryTransport`) and assert that `tools/list_changed` notifications
// + the `tools/list` palette actually flip in step with the server's
// per-session `availableTools[]`. Production callers pass nothing and
// keep the previous stdio + real-API behaviour. When `transport` is
// supplied we also skip the pid lockfile + the "listening on stdio"
// stderr line so tests don't pollute the user's `~/.prepsavant`.
export interface RunMcpServerOptions {
  api?: SamApi;
  transport?: Transport;
}

export async function runMcpServer(opts: RunMcpServerOptions = {}): Promise<void> {
  const cfg = readConfig();
  if (!cfg.token && !opts.api) {
    // We still start the server so the host can introspect tools, but every
    // tool call surfaces a clear error pointing at `prepsavant auth`.
    process.stderr.write(
      "[prepsavant] No device token. Run `prepsavant auth` to authorize.\n",
    );
  }
  const api = opts.api ?? new SamApi(cfg);
  const persona = new PersonaCache(api);
  // Best-effort warmup so the first tool call already has the live persona
  // composed from the server. Failure here is non-fatal; PersonaCache will
  // serve the bundled fallback prompt and retry on demand.
  if (cfg.token) {
    persona.refresh(true).catch(() => {
      // Already logged inside PersonaCache.refresh.
    });
  }

  // Helper: every Sam-voice sampling pass goes through here so all tools
  // share the same up-to-date system prompt without each one having to
  // remember to re-poll.
  const samplingSystemPrompt = async (): Promise<string> => {
    const resolved = await persona.refresh();
    return resolved.systemPrompt;
  };

  // Best-effort enrichment push. Failures are surfaced on stderr but never
  // bubble into the user-visible tool response — the runner has already done
  // its primary job (returning the generated text); the dashboard cache is a
  // nice-to-have copy. Expected 4xx responses (402 missing entitlement, 400
  // bad request from a stale surface enum) are logged at "warn" so a
  // free-tier user — or a runner that ships ahead of a server schema bump —
  // doesn't see a noisy stack trace on every coaching turn.
  const pushEnrichmentBestEffort = async (args: {
    surface: EnrichmentSurface;
    subject?: string;
    body: string;
  }): Promise<void> => {
    if (!args.body.trim()) return;
    try {
      await api.putSamEnrichment({
        surface: args.surface,
        subject: args.subject,
        body: args.body,
        modelLabel: RUNNER_MODEL_LABEL,
      });
    } catch (err) {
      const e = err as { status?: number; message?: string };
      const isExpected4xx =
        typeof e.status === "number" && e.status >= 400 && e.status < 500;
      const tag = isExpected4xx ? "warn" : "error";
      process.stderr.write(
        `[prepsavant] ${tag}: enrichment push (${args.surface}${args.subject ? `:${args.subject}` : ""}) failed: ${e.message ?? err}\n`,
      );
    }
  };

  const server = new McpServer(
    { name: "sam", version: ADAPTER_VERSION },
    {
      capabilities: { tools: {} },
      // Task #1064 — verbatim-relay protocol. The MCP `instructions`
      // field is surfaced to the host model on connect, so this is the
      // earliest opportunity to tell it that during Coached sessions it
      // is a transport for Sam's voice rather than the coach. The
      // critical contract (sentinels, 90s cadence, lastAssistantTurn) is
      // restated on every kickoff brief and every check-in directive,
      // but stating it once up-front makes hosts that bind tools lazily
      // (or skip the kickoff brief on resume) still see the rules.
      instructions: [
        "PrepSavant Sam — split-loop relay protocol (Task #1112 + #1194).",
        "",
        "During a Coached session you are Sam's relay agent — you carry Sam's intent to the candidate, in your own voice when allowed and word-for-word when required.",
        "",
        "1. Use the split-loop pair on every cadence beat: `coached_get_context` (read; cheap) BEFORE you author a turn, then `coached_record_turn` (write) immediately after you speak so the server can bucket your reply into the session's `directiveCompliance` rollup. The runner pushes proactive stall nudges + 50/75/90% time warnings out-of-band via MCP `notifications/message` — surface those when they arrive.",
        "2. Each directive ships `intent`, `constraints`, `suggestedWording`, and `mustBeVerbatim`. Honour `intent` and every entry in `constraints` on every directive.",
        "3. When `mustBeVerbatim:true`, `suggestedWording` is wrapped in `<<<SAM_VERBATIM>>> ... <<<END_SAM_VERBATIM>>>` sentinels — copy that block into your very next assistant turn byte-for-byte (sentinels included). Currently the verbatim allow-list is the safety/contract set: kickoff lines, the session contract, mode-framing, local-execution warning, `submit_pasted_code`, and `missed_heartbeat`.",
        "4. When `mustBeVerbatim:false`, you MAY paraphrase `suggestedWording` to match your conversational tone, provided every `constraints` entry is preserved.",
        "5. Never produce, edit, refactor, or paste the user's solution code in chat. Sam's persona forbids it.",
        "6. Install the bundled IDE rule files (Cursor) when `coached_start_session` reports a successful install — they restate this protocol where the host can re-read it.",
      ].join("\n"),
    },
  );

  // ---------------------------------------------------------------------
  // Task #1144 — Dynamic per-session tool advertisement.
  //
  // The server publishes `availableTools[]` and bumps
  // `capabilitySetVersion` on every `*_get_context` response. The runner
  // mirrors that list onto its MCP tool palette so the host only sees
  // the tools that are valid for the current phase (e.g. exactly one of
  // `*_continue_practice` / `*_wrap_up_now` at any time, and the open-
  // practice writes get pulled once an AI-Assisted session enters wrap
  // up). The server-side 409 rejection path is kept as defence in depth.
  //
  // The runner serves a single MCP connection, so the advertised tool
  // palette is connection-global and reflects the most recently
  // refreshed session context per family. We keep one
  // `{sessionId, version}` slot per family and re-apply whenever EITHER
  // the active sessionId changes OR the server bumps
  // `capabilitySetVersion`; back-to-back reads with the same tuple are
  // a no-op so we don't spam `tools/list_changed`. Interleaving two
  // live sessions of the same family on one runner is not a supported
  // mode (one host, one chat) — the last `*_get_context` wins.
  // ---------------------------------------------------------------------
  type GatedFamily = "coached" | "ai_assisted";
  const gatedTools: Record<GatedFamily, Map<string, RegisteredTool>> = {
    coached: new Map(),
    ai_assisted: new Map(),
  };
  const capabilityState: Record<
    GatedFamily,
    { sessionId: string | null; version: number }
  > = {
    coached: { sessionId: null, version: -1 },
    ai_assisted: { sessionId: null, version: -1 },
  };

  function registerGated(
    family: GatedFamily,
    name: string,
    tool: RegisteredTool,
  ): RegisteredTool {
    gatedTools[family].set(name, tool);
    return tool;
  }

  function applyAvailableTools(
    family: GatedFamily,
    sessionId: string,
    availableTools: ReadonlyArray<string>,
    capabilitySetVersion: number,
  ): void {
    const state = capabilityState[family];
    // Re-apply if the session changed OR the version bumped.
    if (
      state.sessionId === sessionId &&
      state.version === capabilitySetVersion
    ) {
      return;
    }
    const allowed = new Set(availableTools);
    for (const [name, tool] of gatedTools[family]) {
      const wantEnabled = allowed.has(name);
      if (wantEnabled && !tool.enabled) {
        try {
          tool.enable();
        } catch (err) {
          process.stderr.write(
            `[prepsavant] failed to enable ${name}: ${err instanceof Error ? err.message : String(err)}\n`,
          );
        }
      } else if (!wantEnabled && tool.enabled) {
        try {
          tool.disable();
        } catch (err) {
          process.stderr.write(
            `[prepsavant] failed to disable ${name}: ${err instanceof Error ? err.message : String(err)}\n`,
          );
        }
      }
    }
    state.sessionId = sessionId;
    state.version = capabilitySetVersion;
  }

  function resetGatedTools(family: GatedFamily): void {
    for (const [, tool] of gatedTools[family]) {
      if (!tool.enabled) {
        try {
          tool.enable();
        } catch {
          // best effort
        }
      }
    }
    capabilityState[family] = { sessionId: null, version: -1 };
  }

  // ---------------------------------------------------------------------
  // Legacy `practice_*` tool aliases were REMOVED in 0.5.0. The canonical
  // Coached tools below replace them 1:1 with the exception of submit:
  //
  //   practice_list_questions → coached_pick_question
  //   practice_start_session  → coached_start_session
  //   practice_request_hint   → coached_ask
  //   practice_check_in       → coached_check_in
  //   practice_end_session    → coached_end_session
  //   practice_submit_attempt → (no equivalent — Coached sessions submit via
  //                              the host editor's run/test tools)
  //
  // Hosts pinned to the old names will see "tool not found" until they
  // migrate to the `coached_*` names. See the §coached.tool-aliases
  // section of `artifacts/sam/CONTRACTS.md` for the rollout history.
  //
  // Task #794 note: the roleFamily / language / topic / difficulty filter
  // set originally added to `practice_list_questions` lives on inside
  // `coached_pick_question` below, so the question-selection turn still
  // honours candidate filters like "easy backend Python".
  // ---------------------------------------------------------------------

  // The pushAttempt grading path (sandbox + review/probe sampling) used to be
  // exposed as `practice_submit_attempt`. It is intentionally NOT re-registered
  // under a `coached_*` name — Coached submission rides on the host editor's
  // own run/test tools. The grading code paths (`api.pushAttempt`,
  // `buildReviewGrounding`, `pushEnrichmentBestEffort`) remain available for
  // any future caller that wants to reintroduce a runner-driven submit flow.

  // =====================================================================
  // COACHED MODE TOOLS
  // These tools run the Coached session lifecycle entirely inside the user's
  // real editor + AI chat host (Cursor, Claude Desktop, Codex). Sam watches
  // the project passively and delivers nudges when the user stalls. AI usage
  // during a Coached session is detected and flagged in the recap, not blocked.
  // =====================================================================

  // ---------------------------------------------------------------------
  // coached_pick_question — browse and filter available questions from chat.
  // A user can type "give me a coached question for [role/topic]" and Sam
  // returns matching questions without opening the webapp.
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_pick_question",
    {
      description:
        "List interview-prep questions available for a Coached session, optionally filtered by role family, difficulty, language, topic, or company. The host MUST NOT infer or pre-select a question from the user's currently open file, editor context, visible code, or any other editor signal — question selection is the API's job, not the host's. Always call this tool and pick from the returned list (or accept an explicit user request that names a question by id/title). The fact that the candidate has, say, `shortest_alternating_paths.py` open in the editor is NOT a signal about which problem they want to practice. Returns questions the user can pick from to start a Coached session via coached_start_session. To discover valid `company` values when the candidate names a target firm, call coached_list_companies first — this tool returns an EMPTY list (not a difficulty-only fallback) when no question is tagged to the named company, so you must NOT invent a match.",
      inputSchema: {
        roleFamily: z
          .enum(["swe", "data", "ml", "infra", "mobile", "security", "other"])
          .optional(),
        difficulty: z.enum(["easy", "medium", "hard"]).optional(),
        language: z
          .enum(["python", "javascript", "typescript"])
          .optional(),
        topic: z.string().optional(),
        // Task #1061 — accepts a company id, slug, or case-insensitive
        // name. The API resolves it server-side against the canonical
        // companies table; pass the user's literal phrasing
        // ("Anthropic", "stripe", "co_xyz") rather than guessing a slug.
        company: z.string().optional(),
      },
    },
    async (args) => {
      const raw = await api.listQuestions({
        roleFamily: args.roleFamily,
        language: args.language,
        difficulty: args.difficulty,
        topic: args.topic,
        company: args.company,
      });
      const items = raw.items;
      if (items.length === 0) {
        // Task #1061 — when the candidate explicitly named a company, the
        // most likely cause of an empty result is an unknown / mistyped
        // company (the server returns [] rather than silently dropping
        // the filter). Direct the host to coached_list_companies before
        // it offers to relax the filter so we don't lose the candidate's
        // signal about the firm they're targeting.
        if (args.company) {
          return asText(
            `No questions are tagged to company "${args.company}". Call coached_list_companies to see which companies have tagged questions, then retry with one of those id/slug/name values — do NOT silently drop the company filter or invent a different match.`,
          );
        }
        return asText(
          "No questions match those filters. Try removing one of the filters or ask with no filters to see all questions.",
        );
      }
      const lines = items.map(
        (q) =>
          `${q.id}\t${q.title} [${q.roleFamily}] (${q.languages.join(", ")})`,
      );
      return asText(
        [
          `Found ${items.length} question(s). Pick one and call coached_start_session with its id.`,
          "",
          ...lines,
        ].join("\n"),
      );
    },
  );

  // ---------------------------------------------------------------------
  // coached_orient — mode-framing turn (Task #794). Returns the verbatim
  // SAM_VOICE.coached_mode_framing line plus the three mode summaries so
  // the host can either render them as prose or surface a picker. Hosts
  // MUST call this and speak `samVoiceLine` verbatim before
  // coached_start_session whenever the candidate's opener is generic
  // ("I want to practice", "let's do a coding round").
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_orient",
    {
      description:
        "Mode framing for the Coached cold-open. Returns the orient framing intent + constraints + suggested wording plus the three mode options (coached, study, ai_assisted). The host MUST call this before coached_start_session whenever the candidate's opener is generic and they have NOT named a mode. The host AUTHORS its own opener that satisfies the listed constraints — it does NOT have to relay the suggestedWording verbatim. Until the candidate has explicitly named both a mode AND a question, the host MUST NOT discuss, explain, preview, or coach on any problem, and MUST NOT use the user's currently open file, editor tabs, or any visible code as a hint about what the candidate wants to practice — open-file context is NOT a proxy for question selection.",
      inputSchema: {},
    },
    async () => {
      const orient = await api.coachedOrient();
      // Task #1115 (Phase 4) — host-driven opener. The server's
      // `framing` block carries the contractual intent + constraints
      // only; `suggestedWording` is empty by design (no server-
      // authored prose on the orient surface). The host authors the
      // actual opener turn itself from `intent` + `constraints` +
      // `modes[]`. The deprecated `samVoiceLine` field is no longer
      // emitted by the server (≥1.2.0); the type is retained on the
      // client one release for parse-back-compat with any cached
      // response objects.
      const framing = orient.framing ?? {
        action: "coached_mode_framing",
        intent:
          "Welcome the candidate, name the three available modes, and ask which one they want.",
        constraints: [
          "Mention all three modes: coached, study, ai_assisted.",
          "Keep the opener under three sentences.",
          "Do not pre-pick a mode; let the candidate choose.",
        ],
        // Task #1115 (Phase 4) — no server-authored prose. The
        // fallback below is only reached if the server omits the
        // `framing` block entirely (impossible post-cutover with
        // floor ≥1.2.0 + this runner version).
        suggestedWording: "",
        mustBeVerbatim: false,
      };
      const lines = [
        `action: ${framing.action}`,
        `mustBeVerbatim: ${framing.mustBeVerbatim ? "true" : "false"} — author your own opener that satisfies every constraint below. There is NO server-supplied wording for this surface; do not invent one or relay any cached value verbatim.`,
        "",
        "intent:",
        `  ${framing.intent}`,
        "",
        "constraints:",
        ...framing.constraints.map((c) => `  - ${c}`),
        "",
        "modes:",
        // Task #1061 — surface the canonical `nextTool` slug for each mode
        // so the host branches on the right tool family (coached_*,
        // study_*, ai_assisted_*) instead of falling back to coached_*
        // for every mode.
        ...orient.modes.map(
          (m) => `- ${m.slug} (next tool: ${m.nextTool}): ${m.oneLineSummary}`,
        ),
      ];
      return asText(lines.join("\n"));
    },
  );

  // ---------------------------------------------------------------------
  // coached_list_companies — Task #1061. Companies that have at least one
  // tagged question, so the host can convert "I want an Anthropic
  // question" into a valid coached_pick_question company filter without
  // guessing a slug or hallucinating a match.
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_list_companies",
    {
      description:
        "List companies that have at least one tagged interview question. Use this to discover valid `company` values for coached_pick_question whenever the candidate names a target firm — DO NOT guess slugs. Returns rows of `id\\tname (slug) — N question(s)` sorted by question count. An empty result means no question is currently tagged to any company; surface that to the candidate rather than silently dropping the company filter.",
      inputSchema: {},
    },
    async () => {
      const { items } = await api.listCompanies();
      if (items.length === 0) {
        return asText(
          "No companies have tagged questions yet. Drop the company filter and pick from the full bank, or tell the candidate the bank does not have a company-specific question right now.",
        );
      }
      const lines = items.map(
        (c) => `${c.id}\t${c.name} (${c.slug}) — ${c.questionCount} question(s)`,
      );
      return asText(
        [
          `Found ${items.length} compan${items.length === 1 ? "y" : "ies"} with tagged questions. Pass the id, slug, or name to coached_pick_question's \`company\` filter.`,
          "",
          ...lines,
        ].join("\n"),
      );
    },
  );

  // ---------------------------------------------------------------------
  // coached_start_session — start a Coached session entirely from chat.
  // Delivers the question + brief into the AI chat so the user never has
  // to open the webapp. Optionally accepts workspaceDir to enable passive
  // file-system watching for stall detection.
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_start_session",
    {
      description:
        "Start a new Coached session for a given question. Delivers the question prompt and session brief into chat. The host should follow the HOST INSTRUCTIONS in the response to drive coaching nudges. The host MUST NOT preview, discuss, summarize, or explain the question before calling this tool — the canonical question prompt is delivered by THIS tool's response, not by the host's own narration. The host MUST NOT derive `questionId` from the user's currently open file, editor tabs, or any visible code; `questionId` MUST come from a prior `coached_pick_question` call or from an explicit user request that names the question by id or title. After this tool returns is the only point at which file/editor context becomes relevant — and even then only via the runner's diff-aware nudge machinery, not via the host fabricating its own coaching from open files. Pass workDir (absolute path to the project folder) to enable stall detection via file-system watching; defaults to the runner's current working directory when omitted. `workspaceDir` is accepted as a backward-compatible alias.",
      inputSchema: {
        questionId: z.string(),
        companyId: z.string().optional(),
        targetDurationMinutes: z.number().int().min(5).max(180).optional(),
        workDir: z.string().optional(),
        // Backward-compatible alias for hosts pinned to the older field name.
        // `workDir` wins when both are present.
        workspaceDir: z.string().optional(),
      },
    },
    async (args) => {
      const start = await api.startSession({
        questionId: args.questionId,
        companyId: args.companyId,
        targetDurationMinutes: args.targetDurationMinutes,
      });
      const detail = (await api.getSession(start.sessionId)) as {
        question?: { title?: string; prompt?: string };
        kickoffBriefVerbatim?: string;
      };

      const questionTitle = detail.question?.title ?? "Interview question";
      const questionPrompt = detail.question?.prompt ?? "";

      const coachedState = startCoachedSession({
        sessionId: start.sessionId,
        questionId: args.questionId,
        questionTitle,
        questionPrompt,
        workspaceDir: resolveCoachedWorkDir(args),
        ...(typeof args.targetDurationMinutes === "number"
          ? { targetDurationMinutes: args.targetDurationMinutes }
          : {}),
      });

      // Task #1169 (Cursor-first M4) — boot the per-session local
      // cadence loop. This is the runner-as-system-of-record switch:
      // proactive stall nudges + 50/75/90% time warnings now fire
      // from a local timer, pushed to the host out-of-band via MCP
      // server-initiated `notifications/message`. Task #1194 (M8
      // runtime) retired the demoted `coached_check_in` queue
      // drainer — Cursor surfaces MCP notifications natively, and
      // Cursor is now the sole supported AI-Assisted host.
      bootCoachedCadenceLoop(coachedState, { mcp: server });

      // Task #1401 — IDE rule install is retired. The runner now owns
      // the terminal and drives Sam directly; there's no MCP host that
      // needs the relay-protocol prose written into `.cursor/rules/`.
      // `installIdeRulesBestEffort` is preserved as a no-op for one
      // release so any in-flight third-party caller doesn't ENOENT.

      // Task #1401 — the kickoff brief is now consumed by the
      // runner-driven terminal coach, which strips any legacy HOST
      // INSTRUCTIONS prose before printing. We always prefer the
      // canonical `kickoffBriefVerbatim` from the API (still authored
      // there for the one-release grace window), and fall back to a
      // minimal title + prompt block when the API omits it. The
      // protocol framing the old fallback restated has been retired:
      // there is no MCP-host driving Sam any more.
      const verbatim = detail.kickoffBriefVerbatim?.trim();
      const brief = verbatim
        ? [`session_id: ${start.sessionId}`, "", verbatim].join("\n")
        : [
            `session_id: ${start.sessionId}`,
            "",
            `# ${questionTitle}`,
            "",
            questionPrompt,
            "",
            args.targetDurationMinutes
              ? `Timed session: ${args.targetDurationMinutes} minutes.`
              : "",
          ]
            .filter(Boolean)
            .join("\n");

      return asText(brief);
    },
  );

  // ---------------------------------------------------------------------
  // coached_check_in — RETIRED in @prepsavant/mcp@1.9.0 (Task #1194,
  // Cursor-first M8 runtime). This tool was demoted to a no-op queue
  // drainer in 1.5.0 (Task #1169) and is now removed entirely. Hosts
  // must use the split-loop pair (coached_get_context +
  // coached_record_turn) and surface runner-pushed MCP
  // notifications/message for cadence. Pre-1.9.0 callers receive
  // `426 runner_upgrade_required` from the server; the floor is
  // raised in lockstep.
  // ---------------------------------------------------------------------

  // ---------------------------------------------------------------------
  // coached_ask — clarifying questions about the problem, answered by Sam
  // in the study/coach persona. Available at any time during a Coached
  // session. Sam answers without giving away the solution.
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_ask",
    {
      description:
        "Ask Sam a clarifying question about the current Coached session's problem. Sam answers in the coaching persona — explains concepts, gives hints when prompted, but does not hand over a full solution unprompted. Pass the sessionId so Sam can scope the answer to the right problem.",
      inputSchema: {
        sessionId: z.string(),
        question: z.string().min(1),
      },
    },
    async (args) => {
      const state = getCoachedSession(args.sessionId);
      let questionContext = "";
      if (state) {
        questionContext = `\n\nProblem being coached:\nTitle: ${state.questionTitle}\n\n${state.questionPrompt}`;
      } else {
        try {
          const detail = (await api.getSession(args.sessionId)) as {
            question?: { title?: string; prompt?: string };
          };
          if (detail.question) {
            questionContext = `\n\nProblem being coached:\nTitle: ${detail.question.title ?? ""}\n\n${detail.question.prompt ?? ""}`;
          }
        } catch {
        }
      }

      const systemPrompt = await samplingSystemPrompt();
      const userPrompt = [
        `The user is in a Coached session and has a clarifying question about the problem. Answer it in Sam's coaching persona — explain concepts freely, give hints when explicitly requested, but do not hand over a full working solution unless the user explicitly asks to switch to explanation mode.`,
        questionContext,
        `\nUser's question: ${args.question}`,
      ].join("");

      const sampling = await sampleSamVoice(
        server.server,
        systemPrompt,
        userPrompt,
        "I can't answer that right now. Try rephrasing or ask in the webapp.",
      );
      return asText(sampling.text);
    },
  );

  // Task #1401 — `coached_get_context` and `coached_record_turn` are
  // no longer registered on the MCP tool palette. The runner-driven
  // terminal coach (see `coached/terminal-coach.ts`) now owns the
  // cadence loop and speaks Sam-tagged colored lines straight into
  // the user's shell, so an MCP host has nothing to drive any more.
  // The HTTP endpoints (`POST /runner/sessions/:id/coached/context`
  // / `…/turns`) stay live for one release of grace so any in-flight
  // session adopted by a pre-2.0.0 runner can still drain. Once the
  // floor (`MIN_SUPPORTED_RUNNER_VERSION`) bakes in 2.0.0 and the
  // audit-log tells us split-loop calls have stopped, we'll delete
  // the HTTP routes too.

  // ---------------------------------------------------------------------
  // Task #1112 (Phase 3b) — capability-gated escape hatches.
  //
  // `coached_say_exactly(tokenId)` is the verbatim relay path. The host
  // reads `verbatimTokens[]` on the matching `coached_get_context`
  // response and expands one by passing back its `tokenId` (and SHOULD
  // echo `contextSnapshotId` so a token minted against a stale snapshot
  // is rejected with `rejectReason: "stale_context"`). The server
  // returns `{ expanded, text }` — the host MUST relay `text`
  // byte-for-byte as Sam's next assistant turn.
  //
  // `coached_continue_practice` and `coached_wrap_up_now` are mutually
  // exclusive: the server advertises exactly one of them in
  // `availableTools` based on whether the timed session has crossed
  // its target duration (`wrapUpRequired`). Calls out of phase are
  // rejected with 409.
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_say_exactly",
    {
      description:
        "Task #1112 (Phase 3b) — expand a server-minted verbatim token. Read `verbatimTokens[]` on the matching `coached_get_context` response, then call this with the chosen `tokenId` (and echo the same `contextSnapshotId` you read alongside it). On success returns `{ expanded: true, text }` — relay `text` byte-for-byte as Sam's next assistant turn. On rejection returns `{ expanded: false, rejectReason }` (`unknown_token` / `consumed` / `stale_context`); re-read context and retry with the freshest token.",
      inputSchema: {
        sessionId: z.string(),
        tokenId: z.string(),
        contextSnapshotId: z.string().optional(),
      },
    },
    async (args) => {
      const result = await api.coachedSayExactly(args.sessionId, {
        tokenId: args.tokenId,
        ...(args.contextSnapshotId !== undefined
          ? { contextSnapshotId: args.contextSnapshotId }
          : {}),
      });
      return asText(JSON.stringify(result));
    },
  );

  registerGated(
    "coached",
    "coached_continue_practice",
    server.registerTool(
      "coached_continue_practice",
      {
        description:
          "Task #1112 (Phase 3b) — capability-gated still-in-practice acknowledgement. Available only when `coachedWrapUpRequired === false` on the latest `coached_get_context` response (the timed session has NOT yet crossed its target duration). Use this to assert open-practice phase before a long sequence of coaching turns. Calls out of phase return `{ ok: false, rejectReason: \"wrap_up_required\" }`.",
        inputSchema: { sessionId: z.string() },
      },
      async (args) => {
        const result = await api.coachedContinuePractice(args.sessionId);
        return asText(JSON.stringify(result));
      },
    ),
  );

  registerGated(
    "coached",
    "coached_wrap_up_now",
    server.registerTool(
      "coached_wrap_up_now",
      {
        description:
          "Task #1112 (Phase 3b) — capability-gated wrap-up. Available only when `coachedWrapUpRequired === true` on the latest `coached_get_context` response (the timed session has crossed its target duration). Optionally pass a host-authored closing `message`. Calls out of phase return `{ ok: false, rejectReason: \"not_in_wrap_up_phase\" }` — re-read context and continue practice instead.",
        inputSchema: {
          sessionId: z.string(),
          message: z.string().optional(),
        },
      },
      async (args) => {
        const result = await api.coachedWrapUpNow(args.sessionId, {
          ...(args.message !== undefined ? { message: args.message } : {}),
        });
        return asText(JSON.stringify(result));
      },
    ),
  );

  // ---------------------------------------------------------------------
  // coached_end_session — end session + deliver in-chat post-mortem.
  // Sam walks through what happened: score, what was hit/missed, and
  // an explicit offer to continue the debrief via coached_ask.
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_end_session",
    {
      description:
        "End the active Coached session and receive an in-chat post-mortem from Sam: score summary, what was hit or missed, AI assistance flag (if any), and an invitation to ask follow-up questions via coached_ask.",
      inputSchema: { sessionId: z.string() },
    },
    async (args) => {
      const state = endCoachedSession(args.sessionId);
      // Task #1144 — re-enable phase-gated coached tools for the next
      // session, so a fresh `coached_start_session` does not inherit the
      // disabled state from a prior wrap-up.
      resetGatedTools("coached");

      // End the session first so the server-side row reflects the final
      // status before we fetch detail. The detail call is the
      // authoritative source of truth for AI-assist counts (they're
      // posted via /coached-events from outside the runner's in-memory
      // state, e.g. by host-side hooks).
      // Task #1169 (Cursor-first M4) — runner-authored rolling recap
      // draft. Posted alongside the end-session call so the api-server
      // has the local view (file-edit timeline, stall nudges,
      // time-warning fires, AI-assist beats) without having to
      // reconstruct it from forwarded events. Unknown fields are
      // ignored server-side today; M5 wires them into the post-mortem
      // surface. Empty / no-state ends fall back to the legacy POST
      // shape.
      const recapDraft = state
        ? {
            sessionId: args.sessionId,
            startedAt: state.startedAt,
            endedAt: Date.now(),
            targetDurationMs: state.targetDurationMs,
            aiAssistCount: state.aiAssistCount,
            aiAssistSummaries: state.aiAssistSummaries,
            hintLevelFired: state.hintLevelFired,
            events: state.recapEvents,
          }
        : undefined;
      await api
        .endSession(args.sessionId, recapDraft ? { recapDraft } : undefined)
        .catch(() => {});

      // Task #1176 — best-effort Cursor export auto-upload. Failures
      // are queued for retry on next runner start; the outcome is
      // surfaced to the user via stderr alongside session-end output.
      try {
        const { autoUploadCursorExport } = await import(
          "./cursor-export/upload.js"
        );
        const result = await autoUploadCursorExport({
          api,
          sessionId: args.sessionId,
          ...(state?.workspaceDir
            ? { workspaceDir: state.workspaceDir as string }
            : {}),
          source: "auto",
        });
        if (result.status === "uploaded") {
          process.stderr.write(
            `[cursor-export] uploaded ${result.sizeBytes ?? "?"} bytes from ${result.sourcePath}\n`,
          );
        } else if (result.status === "not_found") {
          process.stderr.write(
            `[cursor-export] could not locate a Cursor export — will retry on next runner start. Run \`prepsavant upload-cursor-export --session-id ${args.sessionId} --file <path>\` to upload manually.\n`,
          );
        } else {
          process.stderr.write(
            `[cursor-export] upload failed (${result.reason ?? "unknown"}) — queued for automatic retry on next runner start.\n`,
          );
        }
      } catch (err) {
        // Top-level failure (e.g. dynamic import error) — still surface
        // it to the user so they know what happened.
        process.stderr.write(
          `[cursor-export] auto-upload errored: ${(err as Error).message} — queued for automatic retry on next runner start.\n`,
        );
        try {
          const { enqueue } = await import("./cursor-export/pending-queue.js");
          enqueue({
            sessionId: args.sessionId,
            filePath: null,
            reason: `outer_error: ${(err as Error).message}`,
          });
        } catch {
          /* best-effort */
        }
      }

      let detail: {
        session?: {
          attemptsTotal?: number;
          hintsUsed?: number;
          passedLatest?: boolean;
          coachedAiAssistDetected?: boolean;
          coachedAiAssistCount?: number;
          coachedStallNudgeCount?: number;
          // Per-session chat-activity counters (Task #797). Used to
          // pick the chat-reviewed vs abandoned recap branch and to
          // populate the structured summary fields on
          // CoachedEndSessionSummary.
          practiceCheckInCount?: number;
          pastedCodeOffers?: number;
        };
        question?: { title?: string; reviewKind?: "tests" | "rubric" | null };
        attempts?: Array<{ outcome?: string }>;
        hints?: Array<unknown>;
      } = {};
      try {
        detail = (await api.getSession(args.sessionId)) as typeof detail;
      } catch {
      }

      // Prefer server-authoritative AI-assist counts; fall back to the
      // runner's in-memory state if the detail fetch failed.
      const serverAiAssistCount = detail.session?.coachedAiAssistCount;
      const serverAiAssistDetected = detail.session?.coachedAiAssistDetected;
      const inMemoryAiAssistCount = state?.aiAssistCount ?? 0;
      const aiAssistCount =
        typeof serverAiAssistCount === "number"
          ? serverAiAssistCount
          : inMemoryAiAssistCount;
      const aiAssistDetected =
        typeof serverAiAssistDetected === "boolean"
          ? serverAiAssistDetected
          : inMemoryAiAssistCount > 0;
      const aiAssistSummaries = state?.aiAssistSummaries ?? [];
      const questionTitle =
        detail.question?.title ?? state?.questionTitle ?? "the problem";
      // Task #1163 — let the post-mortem swap "hidden tests" → rubric
      // wording when this question is graded by rubric instead of
      // pinned tests. Falls through to undefined (and the helper's
      // historic "tests" default) when the detail fetch failed.
      const reviewKind = detail.question?.reviewKind ?? undefined;
      const attemptsTotal = detail.session?.attemptsTotal ?? detail.attempts?.length ?? 0;
      const hintsUsed = detail.session?.hintsUsed ?? detail.hints?.length ?? 0;
      const passedLatest = detail.session?.passedLatest;
      // Stall-nudge counts only live server-side (Task #564) — the runner
      // doesn't keep an in-memory accumulator. If the detail fetch failed,
      // fall back to 0 rather than fabricating a value.
      const stallNudgeCount = detail.session?.coachedStallNudgeCount ?? 0;
      // Chat-activity counters (Task #797). Server-side only — used to
      // pick the chat-reviewed vs abandoned recap branch when the
      // candidate ended without ever submitting code through the runner.
      const checkInCount = detail.session?.practiceCheckInCount ?? 0;
      const pastedCodeOffers = detail.session?.pastedCodeOffers ?? 0;

      const postMortem = buildCoachedPostMortemText({
        questionTitle,
        reviewKind,
        attemptsTotal,
        hintsUsed,
        passedLatest,
        aiAssistDetected,
        aiAssistCount,
        aiAssistSummaries,
        stallNudgeCount,
        checkInCount,
        pastedCodeOffers,
        checkInDiffSummaries: state?.checkInDiffSummaries ?? [],
      });

      // Task #800 / #804 — auto-summarize the rolling session memory.
      //
      // We sample the host with the prior session memory + this
      // session's outcome and ask it to rewrite the memory under the
      // 2,000-character cap (preferring recent learnings, dropping
      // oldest entries first when something must go). The rewritten
      // body is then PATCHed back to /profile/session-memory.
      //
      // Failure modes — all best-effort, none of them block the
      // post-mortem return (the host has already received the tool
      // result by the time the rewrite runs):
      //   - GET /profile 404 → no profile yet, skip the rewrite.
      //   - host refused sampling → log to stderr, keep prior memory.
      //   - host returned > cap → log to stderr, keep prior memory
      //     (we deliberately do NOT trim — a half-cut bullet would
      //     destroy more context than leaving the prior body alone).
      //   - PATCH 413 (server cap) → log to stderr and skip.
      //   - any other API error → log to stderr and skip.
      //
      // The rewrite uses `SESSION_MEMORY_REWRITE_INSTRUCTION` as the
      // sampling system directive (NOT the live Sam-voice persona) so
      // the host model knows the cap and the "drop oldest first" rule.
      // The contract is unit-tested in
      // `coached-session-memory-rewrite.test.ts` via injectable deps.
      void rewriteSessionMemoryBestEffort({
        api,
        server: server.server,
        questionTitle,
        attemptsTotal,
        hintsUsed,
        passedLatest,
        aiAssistDetected,
      });

      return asText(
        formatCoachedEndSessionResponse({
          session_id: args.sessionId,
          status: "ended",
          coachedAiAssistDetected: aiAssistDetected,
          coachedAiAssistCount: aiAssistCount,
          coachedStallNudgeCount: stallNudgeCount,
          coachedCheckInCount: checkInCount,
          coachedPastedCodeOffers: pastedCodeOffers,
          postMortem,
        }),
      );
    },
  );

  // ---------------------------------------------------------------------
  // enrich_job — push why-fit + application-angle for a job.
  // ---------------------------------------------------------------------
  server.registerTool(
    "enrich_job",
    {
      description:
        "Generate Sam-voice why-fit and application-angle text for a job and push them back to the Sam dashboard. Pass calibration fields when available — they let Sam apply the Search spec's 5-dimension fit-score reasoning and name concrete risks.",
      inputSchema: {
        jobId: z.string(),
        jobTitle: z.string(),
        company: z.string(),
        jobDescription: z.string().optional(),
        candidateProfileSummary: z.string(),
        // Structured calibration fields from the candidate's profile.
        // All optional: Sam degrades gracefully when they are absent.
        currentProofPoints: z.array(z.string()).optional(),
        weakSpots: z.array(z.string()).optional(),
        calibratedTargetIndustries: z.array(z.string()).optional(),
        compFloor: z.number().optional(),
        sponsorshipNeed: z.boolean().optional(),
        geoPreference: z.string().optional(),
      },
    },
    async (args) => {
      const grounding = buildJobEnrichmentGrounding({
        jobTitle: args.jobTitle,
        company: args.company,
        jobDescription: args.jobDescription,
        candidateProfileSummary: args.candidateProfileSummary,
        currentProofPoints: args.currentProofPoints,
        weakSpots: args.weakSpots,
        calibratedTargetIndustries: args.calibratedTargetIndustries,
        compFloor: args.compFloor,
        sponsorshipNeed: args.sponsorshipNeed,
        geoPreference: args.geoPreference,
      });
      const sampling = await sampleSamVoice(
        server.server,
        await samplingSystemPrompt(),
        grounding,
        "",
      );
      let whyYouFit = "";
      let applicationAngle = "";
      let risks: string[] = [];
      let firstActionAngle = "";
      let source: "runner_sampling" | "runner_fallback" = "runner_fallback";
      if (sampling.source === "runner_sampling") {
        const parsed = tryExtractJson<{
          why_you_fit?: string;
          application_angle?: string;
          risks?: string[];
          first_action_angle?: string;
        }>(sampling.text);
        whyYouFit = parsed?.why_you_fit ?? sampling.text;
        applicationAngle = parsed?.application_angle ?? "";
        risks = parsed?.risks ?? [];
        firstActionAngle = parsed?.first_action_angle ?? "";
        source = "runner_sampling";
      }
      if (!whyYouFit) {
        return asText(
          "Sam could not generate enrichment locally (host refused sampling and no fallback was provided). Try again from the dashboard.",
        );
      }
      try {
        await api.pushJobEnrichment(args.jobId, {
          whyYouFit,
          applicationAngle,
          source,
        });
      } catch (err) {
        return asText(`Generated text but could not push it: ${(err as Error).message}`);
      }
      // Mirror into the new surface×subject enrichment cache so the
      // dashboard's why-you-fit / application-angle cards flip to the
      // "Generated locally by Sam in your IDE" state. Keep this best-effort
      // — if the user is on a free tier we still want the legacy
      // pushJobEnrichment above to record the result.
      await pushEnrichmentBestEffort({
        surface: "why_you_fit",
        subject: args.jobId,
        body: whyYouFit,
      });
      if (applicationAngle.trim()) {
        await pushEnrichmentBestEffort({
          surface: "application_angle",
          subject: args.jobId,
          body: applicationAngle,
        });
      }
      const outputParts = ["why_you_fit:", whyYouFit, "", "application_angle:", applicationAngle];
      if (firstActionAngle.trim()) {
        outputParts.push("", "first_action:", firstActionAngle);
      }
      if (risks.length > 0) {
        outputParts.push("", "risks:", ...risks.map((r) => `- ${r}`));
      }
      return asText(
        outputParts.join("\n"),
      );
    },
  );

  // ---------------------------------------------------------------------
  // enrich_shortlist — push a one-line annotation onto a shortlist item.
  // ---------------------------------------------------------------------
  server.registerTool(
    "enrich_shortlist",
    {
      description: "Push a Sam-voice annotation onto a shortlist item.",
      inputSchema: {
        shortlistItemId: z.string(),
        prompt: z.string(),
      },
    },
    async (args) => {
      const sampling = await sampleSamVoice(
        server.server,
        await samplingSystemPrompt(),
        args.prompt,
        "",
      );
      if (!sampling.text) {
        return asText("Host refused sampling and no fallback was supplied.");
      }
      try {
        await api.pushShortlistAnnotation(args.shortlistItemId, {
          annotation: sampling.text,
          source: sampling.source,
        });
      } catch (err) {
        return asText(`Generated text but could not push it: ${(err as Error).message}`);
      }
      return asText(sampling.text);
    },
  );

  // ---------------------------------------------------------------------
  // forget_dashboard_copy — clear a previously pushed enrichment row so the
  // dashboard stops showing the locally generated copy and falls back to the
  // server-side template. Useful when the user says "Sam, forget what you
  // said about job X" or when a job's underlying posting changes and the
  // generated copy is no longer accurate.
  // ---------------------------------------------------------------------
  server.registerTool(
    "forget_dashboard_copy",
    {
      description:
        "Forget a previously pushed Sam enrichment for a given surface (and optional subject id) so the dashboard reverts to the template fallback.",
      inputSchema: {
        surface: z.enum(ENRICHMENT_SURFACES),
        subject: z.string().optional(),
      },
    },
    async (args) => {
      // The server's DELETE /sam/enrichment is idempotent — it returns
      // { ok: true } whether or not a matching row existed — so we don't try
      // to distinguish "deleted" from "nothing to delete" in the response.
      try {
        await api.deleteSamEnrichment({
          surface: args.surface,
          subject: args.subject,
        });
        return asText(
          `Forgot ${args.surface}${args.subject ? `:${args.subject}` : ""}.`,
        );
      } catch (err) {
        return asText(
          `Could not forget ${args.surface}: ${(err as Error).message}`,
        );
      }
    },
  );

  // ---------------------------------------------------------------------
  // research_jobs — scan configured target companies' careers pages and
  // push the extracted openings back into the Sam dashboard so they stop
  // appearing as "sample" jobs.
  // ---------------------------------------------------------------------
  server.registerTool(
    "research_jobs",
    {
      description:
        "Scan configured target companies' careers pages and push the openings back to the Sam dashboard. Newly recorded jobs appear in shortlists without the Sample badge. When `targets` is omitted the runner falls back to the local file ~/.prepsavant/research-targets.json and then to the user's saved list on the dashboard. Re-fetched pages whose content hash matches the previous run within the freshness window are skipped to save host-model tokens; pass `force: true` to bypass the cache.",
      inputSchema: {
        targets: z
          .array(
            z.object({
              companyName: z.string(),
              careersUrl: z.string().url(),
              companySlug: z.string().optional(),
              industry: z.string().optional(),
            }),
          )
          .min(1)
          .optional(),
        maxJobsPerCompany: z.number().int().min(1).max(50).optional(),
        notes: z.string().optional(),
        // Bypass the careers-page content-hash cache and force a fresh
        // model extraction for every target.
        force: z.boolean().optional(),
        // Override the default freshness window (in hours). When the
        // cached fetch is younger than this and the hash matches, the
        // model call is skipped. Defaults to 6h.
        cacheTtlHours: z.number().int().min(0).max(168).optional(),
      },
    },
    async (args) => {
      const maxJobs = args.maxJobsPerCompany ?? 20;
      const force = args.force === true;
      const cacheTtlMs = (args.cacheTtlHours ?? 6) * 60 * 60 * 1000;
      const summary: string[] = [];

      // Resolve target list. Order:
      //   1. Explicit `targets` argument (one-off scan).
      //   2. ~/.prepsavant/research-targets.json (per-machine override).
      //   3. GET /api/jobs/research/targets (saved on the dashboard).
      // We expose where the list came from in the summary so users
      // understand why a "no targets argument" call still scanned 5 sites.
      let targets: LocalResearchTarget[] = [];
      let source: "argument" | "local_file" | "saved" = "argument";
      if (args.targets && args.targets.length > 0) {
        targets = args.targets.map((t) => ({
          companyName: t.companyName,
          careersUrl: t.careersUrl,
          companySlug: t.companySlug,
          industry: t.industry,
        }));
        source = "argument";
      } else {
        const local = readLocalResearchTargets();
        if (local && local.length > 0) {
          targets = local;
          source = "local_file";
        } else {
          try {
            const saved = await api.listResearchTargets();
            targets = saved.targets.map((t) => ({
              companyName: t.companyName,
              careersUrl: t.careersUrl,
              companySlug: t.slug,
              industry: t.industry,
            }));
            source = "saved";
          } catch (err) {
            return asText(
              `No targets supplied and could not load saved targets: ${(err as Error).message}`,
            );
          }
        }
      }

      if (targets.length === 0) {
        return asText(
          'No targets to scan. Pass `targets: [{ companyName, careersUrl }, ...]`, drop a JSON file at ~/.prepsavant/research-targets.json, or save a list at /dashboard/job-search/targets.',
        );
      }

      let run: Awaited<ReturnType<typeof api.startResearchRun>>;
      try {
        run = await api.startResearchRun({
          runnerVersion: ADAPTER_VERSION,
          modelHint: "host_sampling",
          notes: args.notes,
        });
      } catch (err) {
        return asText(
          `Could not open a research run: ${(err as Error).message}`,
        );
      }
      summary.push(`run_id: ${run.id}`);
      summary.push(`targets_source: ${source} (${targets.length} companies)`);

      let totalAdded = 0;
      let totalUpdated = 0;
      let totalSkipped = 0;
      let totalUnchanged = 0;
      let companiesAttempted = 0;
      let companiesSucceeded = 0;
      const errors: string[] = [];

      for (let i = 0; i < targets.length; i++) {
        const target = targets[i]!;
        const isLast = i === targets.length - 1;
        companiesAttempted += 1;
        // Every record call carries an explicit `company` descriptor so
        // /admin/research can show a per-company outcome row even when the
        // jobs[] payload is empty (refusal / fetch-error path).
        const companyDescriptor = {
          name: target.companyName,
          slug: target.companySlug,
          careersUrl: target.careersUrl,
        };
        // Build the per-iteration record body so error/refusal branches still
        // count this company toward `companiesScanned` on the server side
        // (the API counts unique slugs in the `jobs[]` it sees). When the
        // body is empty we can't bump that counter, so we fall back to
        // surfacing the attempt via `errorText` instead.
        let recordBody: Parameters<typeof api.recordResearchResult>[1] = {
          jobs: [],
          company: companyDescriptor,
          complete: isLast,
        };
        let outcomeLine = "";
        let errorLine: string | null = null;

        try {
          const page = await fetchCareersPage(target.careersUrl);
          const contentHash = sha256Hex(page);

          // Cache short-circuit: when the freshly-hashed page matches the
          // last successful extract for this (owner, careersUrl) AND the
          // cached fetch is still inside the freshness window, we skip the
          // host-model call entirely. The server-side accounting bumps a
          // dedicated `companiesUnchanged` counter so /admin/research can
          // tell this apart from real fetch/sampling errors.
          let cacheHit = false;
          if (!force) {
            try {
              const cached = await api.getResearchCache(target.careersUrl);
              if (
                cached &&
                cached.contentHash === contentHash &&
                Date.now() - new Date(cached.fetchedAt).getTime() < cacheTtlMs
              ) {
                cacheHit = true;
              }
            } catch {
              // Cache lookup failures are non-fatal; fall through to a
              // normal extraction. The server will recover next time.
            }
          }

          if (cacheHit) {
            recordBody = {
              jobs: [],
              company: companyDescriptor,
              complete: isLast,
              careersUrl: target.careersUrl,
              companyName: target.companyName,
              contentHash,
              skipReason: "unchanged",
            };
            outcomeLine = `${target.companyName}: unchanged since last run — skipped model call`;
          } else {
            const grounding = buildJobResearchGrounding({
              companyName: target.companyName,
              careersUrl: target.careersUrl,
              pageExcerpt: page,
              maxJobs,
            });
            const sampling = await sampleSamVoice(
              server.server,
              SAM_RESEARCH_SYSTEM_PROMPT,
              grounding,
              "",
            );

            if (sampling.source !== "runner_sampling" || !sampling.text) {
              errorLine = `${target.companyName}: host refused sampling — skipped.`;
              recordBody = {
                jobs: [],
                company: companyDescriptor,
                complete: isLast,
                careersUrl: target.careersUrl,
                companyName: target.companyName,
                skipReason: "error",
                errorText: `host_refused_sampling: ${target.companyName}`,
              };
            } else {
              const parsed = tryExtractJson<{ jobs?: unknown[] }>(sampling.text);
              const rawJobs = Array.isArray(parsed?.jobs) ? parsed!.jobs : [];
              const jobs = rawJobs
                .map((j) =>
                  normalizeExtractedJob(j, target, target.careersUrl, maxJobs),
                )
                .filter(
                  (j): j is NonNullable<ReturnType<typeof normalizeExtractedJob>> =>
                    j !== null,
                )
                .slice(0, maxJobs);
              recordBody = {
                jobs,
                company: companyDescriptor,
                complete: isLast,
                careersUrl: target.careersUrl,
                companyName: target.companyName,
                contentHash,
              };
            }
          }
        } catch (err) {
          errorLine = `${target.companyName}: ${(err as Error).message}`;
          recordBody = {
            jobs: [],
            company: companyDescriptor,
            complete: isLast,
            careersUrl: target.careersUrl,
            companyName: target.companyName,
            skipReason: "error",
            errorText: `${target.companyName}: ${(err as Error).message}`,
          };
        }

        // Always record the per-company outcome so the run's accounting and
        // completion flag stay consistent, even on refusal/fetch failure.
        let recordSucceeded = false;
        try {
          const recorded = await api.recordResearchResult(run.id, recordBody);
          recordSucceeded = true;
          totalAdded += recorded.added;
          totalUpdated += recorded.updated;
          totalSkipped += recorded.skipped;
          if (recordBody.skipReason === "unchanged") {
            totalUnchanged += 1;
            companiesSucceeded += 1;
            // outcomeLine already set above; nothing to overwrite.
          } else if (errorLine === null) {
            companiesSucceeded += 1;
            outcomeLine = `${target.companyName}: +${recorded.added} new, ~${recorded.updated} updated, ${recorded.skipped} skipped`;
          }
        } catch (recordErr) {
          errorLine =
            errorLine ??
            `${target.companyName}: record failed — ${(recordErr as Error).message}`;
        }

        // Best-effort finalize: if the LAST per-company record call failed,
        // the run is left in-flight on the server. Send one explicit empty
        // close so the run flips to completed/error and doesn't show as
        // "in-flight forever" in /admin/research.
        if (isLast && !recordSucceeded) {
          try {
            await api.recordResearchResult(run.id, {
              jobs: [],
              company: companyDescriptor,
              complete: true,
              errorText: errorLine ?? "finalize_after_record_failure",
            });
          } catch {
            // Surface via summary; nothing more we can do from the runner.
          }
        }

        if (errorLine) errors.push(errorLine);
        if (outcomeLine) summary.push(outcomeLine);
      }

      summary.push("");
      const unchangedSummary =
        totalUnchanged > 0 ? `, ${totalUnchanged} unchanged (cached)` : "";
      summary.push(
        `Totals: ${totalAdded} added, ${totalUpdated} updated, ${totalSkipped} skipped${unchangedSummary} across ${companiesSucceeded}/${companiesAttempted} companies.`,
      );
      if (errors.length > 0) {
        summary.push("");
        summary.push("Issues:");
        for (const e of errors) summary.push(`  - ${e}`);
      }
      return asText(summary.join("\n"));
    },
  );

  // =====================================================================
  // AI-ASSISTED MODE TOOLS — Task #1061
  // The MCP host (Cursor as of Task #1194) IS the AI in AI-Assisted
  // mode. These tools let the host create a session, drive the
  // split-loop coaching surface, and finalize the session so the
  // dashboard can grade the Cursor chat export. They DELIBERATELY do
  // not refuse to generate code — refusing here is the failure mode
  // AI-Assisted grades the candidate on, not the host.
  //
  // Task #1193 (@prepsavant/mcp@2.0.0) physically retired the
  // `ai_assisted_log_event` / `ai_assisted_snapshot` per-event ingest
  // tools and the in-process Cursor hook capture path. End-of-session
  // evidence now flows through `prepsavant upload-cursor-export`.
  // =====================================================================

  // Capability manifest — replaces the previous import from
  // `./ai-assisted/session.js`, which was deleted alongside the
  // in-process hook capture path in Task #1193.
  function buildCapabilityManifest(tool: string): {
    captures: string[];
    notCaptures: string[];
    toolLabel: string;
    consentVersion: string;
    confidenceCeiling: "high" | "medium" | "low";
    osCaveats: string[];
    toolStatus: "ga" | "beta";
  } {
    return {
      captures: [
        "Cursor chat export uploaded at end of session",
        "Sam's split-loop coaching turns (context + feedback)",
      ],
      notCaptures: [
        "Live in-process Cursor hook events (retired in 2.0.0)",
      ],
      toolLabel: tool === "cursor" ? "Cursor" : tool,
      consentVersion: "2025-05",
      confidenceCeiling: "medium",
      osCaveats: [],
      toolStatus: "beta",
    };
  }

  type AiAssistedSessionState = {
    sessionId: string;
    runnerVersion: string;
    adapterVersion: string;
    tool: string;
    // Task #1416 — set to `true` once the AI-Assisted standing-frame
    // rule files have been written into the candidate's workspace
    // (`.cursor/rules/prepsavant-ai-assisted.mdc`). The runner forwards
    // this to the api-server on every `ai_assisted_get_context` call so
    // the server can suppress the duplicated HOST INSTRUCTIONS prose
    // from the `activeConstraints` payload.
    frameInstalled: boolean;
  };
  const aiAssistedSessions = new Map<string, AiAssistedSessionState>();

  server.registerTool(
    "ai_assisted_start_session",
    {
      description:
        "Start an AI-Assisted session. The candidate has chosen to let YOU (the AI host) drive the work. You DO NOT refuse to generate, edit, or run code — refusing is the exact failure AI-Assisted grades the candidate's prompting on, not the host's policy. Pick the questionId from coached_pick_question (use coached_list_companies first if the candidate named a company). Returns the session id, the verbatim question prompt, and HOST INSTRUCTIONS describing the split-loop coaching tools (ai_assisted_get_context / ai_assisted_record_feedback / ai_assisted_end_session). Per-event ingest tools (ai_assisted_log_event / ai_assisted_snapshot) and the in-process Cursor hook path were retired in @prepsavant/mcp@2.0.0; evidence is now graded from the Cursor chat export uploaded via `prepsavant upload-cursor-export` at end-of-session. Requires the candidate to be on the $299 plan; the server returns 403 entitlement_required otherwise.",
      inputSchema: {
        questionId: z.string(),
        // Task #1194 (Cursor-first M8 runtime) — Cursor is the sole
        // supported AI-Assisted host. The previous claude_code/codex
        // tool labels were retired alongside the hook adapters; only
        // "cursor" is accepted, and start defaults to "cursor".
        tool: z.enum(["cursor"]).optional(),
        toolVersion: z.string().optional(),
        companyId: z.string().optional(),
        targetDurationMinutes: z.number().int().min(5).max(180).optional(),
        // Task #1119 (code-review #5) — optional workspace dir so the
        // installer can write `.cursor/rules/prepsavant-ai-assisted.mdc`
        // and the AI-Assisted SKILL.md / CLAUDE.md managed block into
        // the candidate's project. Mirrors the coached_start_session
        // shape so hosts that already pass workDir for coached can
        // forward the same value here.
        workDir: z.string().optional(),
        workspaceDir: z.string().optional(),
      },
    },
    async (args) => {
      const tool = args.tool ?? "cursor";
      const toolVersion = args.toolVersion ?? "mcp-host";
      const keyPair = generateEphemeralKeyPair();
      const manifest = buildCapabilityManifest(tool);
      const start = await api.startAiAssistedSession({
        questionId: args.questionId,
        companyId: args.companyId,
        targetDurationMinutes: args.targetDurationMinutes,
        aiAssisted: {
          tool,
          toolVersion,
          adapterVersion: ADAPTER_VERSION,
          runnerVersion: ADAPTER_VERSION,
          runnerPublicKey: keyPair.publicKeyBase64Url,
          capabilityManifest: manifest,
        },
      });

      const sessionState: AiAssistedSessionState = {
        sessionId: start.sessionId,
        runnerVersion: ADAPTER_VERSION,
        adapterVersion: ADAPTER_VERSION,
        tool,
        frameInstalled: false,
      };
      aiAssistedSessions.set(start.sessionId, sessionState);

      // Task #1119 (code-review #5) / Task #1416 — best-effort install
      // of the AI-Assisted IDE rule files (Cursor's
      // `.cursor/rules/prepsavant-ai-assisted.mdc`, Claude Code's
      // CLAUDE.md managed block, `.claude/skills/prepsavant-ai-assisted/
      // SKILL.md`) so the host has the family-scoped standing frame
      // available immediately after start. We awa it the install (with
      // a short timeout fallback) so we know whether the rule file
      // actually landed — if it did, the runner forwards
      // `frameInstalled: true` on every `ai_assisted_get_context` call
      // and the api-server suppresses the duplicated HOST INSTRUCTIONS
      // guardrails from `activeConstraints` (Task #1413's safety net).
      // Failures must not block AI-Assisted session start (the
      // server-side hard-fail at session create is the source-of-truth
      // invariant; the installer is a host-side convenience).
      try {
        const installRes = await installAiAssistedIdeRulesBestEffort(
          resolveCoachedWorkDir(args),
          api,
        );
        sessionState.frameInstalled = installRes.installed;
      } catch {
        // Already swallowed inside the helper, but defence-in-depth.
        sessionState.frameInstalled = false;
      }

      let questionPrompt = "";
      let questionTitle = "Interview question";
      try {
        const detail = (await api.getSession(start.sessionId)) as {
          question?: { title?: string; prompt?: string };
        };
        questionTitle = detail.question?.title ?? questionTitle;
        questionPrompt = detail.question?.prompt ?? "";
      } catch {
        // Best-effort — the start response already gave us the session id.
      }

      // Task #1399 — render the polished startup banner (success
      // header / Next steps / quieted question brief / "session live"
      // footer). The HOST INSTRUCTIONS prose that previously trailed
      // this response is intentionally omitted from the user-facing
      // text — the AI host still receives the protocol via two
      // surviving channels:
      //   1. The `.cursor/rules/prepsavant-ai-assisted.mdc` standing
      //      frame installed by `installIdeRulesBestEffort` above
      //      (the AI-Assisted SKILL.md / CLAUDE.md managed block).
      //   2. The `activeConstraints` payload returned by every
      //      `ai_assisted_get_context` call.
      // MCP stdio is non-TTY so `makeColors` auto-disables ANSI here;
      // a future surface that pipes this through a real terminal can
      // pass its own stream and get color for free.
      const colors = makeColors({ isTTY: false });
      // Task #1499 — pull the "How this session works" guide from the
      // SAM_VOICE registry so the Cursor-rendered banner mirrors the
      // dashboard practice page (including the export-into-this-folder
      // instruction). Best-effort — falls back to no guide section on
      // older api-server replicas.
      let instructionGuide: string | null = null;
      try {
        const voice = await api.getSamVoice("practice_ai_assisted_guide");
        instructionGuide = voice?.text ?? null;
      } catch {
        instructionGuide = null;
      }
      return asText(
        renderAiAssistedStartupBanner(
          {
            adapterVersion: ADAPTER_VERSION,
            sessionId: start.sessionId,
            questionTitle,
            questionPrompt,
            ...(args.targetDurationMinutes !== undefined
              ? { targetDurationMinutes: args.targetDurationMinutes }
              : {}),
            instructionGuide,
          },
          colors,
        ),
      );
    },
  );

  // Task #1193 (@prepsavant/mcp@2.0.0) — `ai_assisted_log_event` and
  // `ai_assisted_snapshot` were physically retired alongside the
  // in-process Cursor hook capture path. The dashboard now grades the
  // Cursor chat export uploaded via `prepsavant upload-cursor-export`.

  // Task #1119 — `ai_assisted_check_in` retired in runner v1.0.0. Hosts
  // must use the split-loop pair (`ai_assisted_get_context` +
  // `ai_assisted_record_feedback`) below.

  registerGated(
    "ai_assisted",
    "ai_assisted_get_context",
    server.registerTool(
      "ai_assisted_get_context",
      {
        description:
          "Pure-read AI-Assisted context (Task #1117, Phase 3a). Returns `contextSnapshotId` plus an `evidence` payload (event-log slice, recent attempts/snapshots, last cropped diff snippet, attempts/distinct-failing tests in the recent window, time elapsed/remaining, recent assistant feedback, `priorFeedbackCorrection`) and the active `activeConstraints`. Read this BEFORE you author a feedback turn so you can ground your wording in the same evidence the server would have used. The host MUST echo `contextSnapshotId` on the matching `ai_assisted_record_feedback` write so the server can detect stale-context turns.",
        inputSchema: {
          sessionId: z.string(),
        },
      },
      async (args) => {
        const state = aiAssistedSessions.get(args.sessionId);
        if (!state) {
          return asText(
            `Unknown AI-Assisted session: ${args.sessionId}. Call ai_assisted_start_session first.`,
          );
        }
        try {
          const ctx = await api.getAiAssistedContext(args.sessionId, {
            frameInstalled: state.frameInstalled,
          });
          // Task #1144 — mirror the server's per-session capability
          // set onto the runner's AI-Assisted tool palette so phase-
          // gated tools (`*_continue_practice` / `*_wrap_up_now`,
          // and the open-practice writes) appear/disappear in step
          // with the server.
          applyAvailableTools(
            "ai_assisted",
            args.sessionId,
            ctx.availableTools,
            ctx.capabilitySetVersion,
          );
          return asText(JSON.stringify(ctx));
        } catch (err) {
          return asText(
            `ai_assisted_get_context failed: ${err instanceof Error ? err.message : String(err)}`,
          );
        }
      },
    ),
  );

  registerGated(
    "ai_assisted",
    "ai_assisted_record_feedback",
    server.registerTool(
      "ai_assisted_record_feedback",
      {
        description:
          "Pure-write AI-Assisted feedback turn (Task #1117, Phase 3a). Records the host-authored feedback line. Echo the `contextSnapshotId` you read from `ai_assisted_get_context` so the server can flag the turn `staleContext: true` if a new event or snapshot arrived between read and write. The server runs the directive-mode compliance classifier and stamps `priorFeedbackCorrection` on the next `ai_assisted_get_context`. `feedbackKind` is an optional classifier label (e.g. `feedback_offer`, `progress_ack`, `submission_review`).",
        inputSchema: {
          sessionId: z.string(),
          feedbackText: z.string(),
          feedbackKind: z.string().optional(),
          contextSnapshotId: z.string().optional(),
        },
      },
      async (args) => {
        const state = aiAssistedSessions.get(args.sessionId);
        if (!state) {
          return asText(
            `Unknown AI-Assisted session: ${args.sessionId}. Call ai_assisted_start_session first.`,
          );
        }
        try {
          const result = await api.recordAiAssistedFeedback(args.sessionId, {
            feedbackText: args.feedbackText,
            ...(args.feedbackKind ? { feedbackKind: args.feedbackKind } : {}),
            ...(args.contextSnapshotId
              ? { contextSnapshotId: args.contextSnapshotId }
              : {}),
          });
          return asText(JSON.stringify(result));
        } catch (err) {
          return asText(
            `ai_assisted_record_feedback failed: ${err instanceof Error ? err.message : String(err)}`,
          );
        }
      },
    ),
  );

  // ---------------------------------------------------------------------
  // Task #1118 (Phase 3b) — AI-Assisted capability-gated escape hatches.
  // Mirror of the coached say-exactly / wrap-up-now / continue-practice
  // tools (Task #1112) for AI-Assisted sessions.
  // ---------------------------------------------------------------------
  server.registerTool(
    "ai_assisted_say_exactly",
    {
      description:
        "Task #1118 (Phase 3b) — expand a server-minted verbatim token for an AI-Assisted session. Read `evidence.verbatimTokens[]` on the matching `ai_assisted_get_context` response, then call this with the chosen `tokenId` and echo the same `contextSnapshotId` you read alongside it. The `contextSnapshotId` is REQUIRED — the server uses it to enforce the \"fetch context, then say_exactly next with no intervening writes\" guarantee. On success returns `{ expanded: true, text }` — relay `text` byte-for-byte as Sam's next assistant turn. On rejection returns `{ expanded: false, rejectReason }` (`unknown_token` / `consumed` / `stale_context`); re-read context and retry with the freshest token.",
      inputSchema: {
        sessionId: z.string(),
        tokenId: z.string(),
        contextSnapshotId: z.string(),
      },
    },
    async (args) => {
      const state = aiAssistedSessions.get(args.sessionId);
      if (!state) {
        return asText(
          `Unknown AI-Assisted session: ${args.sessionId}. Call ai_assisted_start_session first.`,
        );
      }
      try {
        const result = await api.aiAssistedSayExactly(args.sessionId, {
          tokenId: args.tokenId,
          contextSnapshotId: args.contextSnapshotId,
        });
        return asText(JSON.stringify(result));
      } catch (err) {
        return asText(
          `ai_assisted_say_exactly failed: ${err instanceof Error ? err.message : String(err)}`,
        );
      }
    },
  );

  registerGated(
    "ai_assisted",
    "ai_assisted_continue_practice",
    server.registerTool(
      "ai_assisted_continue_practice",
      {
        description:
          "Task #1118 (Phase 3b) — capability-gated still-in-practice acknowledgement for an AI-Assisted session. Available only when `evidence.wrapUpRequired === false` on the latest `ai_assisted_get_context` response. Calls out of phase return `{ ok: false, rejectReason: \"wrap_up_required\" }`.",
        inputSchema: { sessionId: z.string() },
      },
      async (args) => {
        const state = aiAssistedSessions.get(args.sessionId);
        if (!state) {
          return asText(
            `Unknown AI-Assisted session: ${args.sessionId}. Call ai_assisted_start_session first.`,
          );
        }
        try {
          const result = await api.aiAssistedContinuePractice(args.sessionId);
          return asText(JSON.stringify(result));
        } catch (err) {
          return asText(
            `ai_assisted_continue_practice failed: ${err instanceof Error ? err.message : String(err)}`,
          );
        }
      },
    ),
  );

  registerGated(
    "ai_assisted",
    "ai_assisted_wrap_up_now",
    server.registerTool(
      "ai_assisted_wrap_up_now",
      {
        description:
          "Task #1118 (Phase 3b) — capability-gated wrap-up for an AI-Assisted session. Available only when `evidence.wrapUpRequired === true` on the latest `ai_assisted_get_context` response. Optionally pass a host-authored closing `message`. Calls out of phase return `{ ok: false, rejectReason: \"not_in_wrap_up_phase\" }`.",
        inputSchema: {
          sessionId: z.string(),
          message: z.string().optional(),
        },
      },
      async (args) => {
        const state = aiAssistedSessions.get(args.sessionId);
        if (!state) {
          return asText(
            `Unknown AI-Assisted session: ${args.sessionId}. Call ai_assisted_start_session first.`,
          );
        }
        try {
          const result = await api.aiAssistedWrapUpNow(args.sessionId, {
            ...(args.message !== undefined ? { message: args.message } : {}),
          });
          return asText(JSON.stringify(result));
        } catch (err) {
          return asText(
            `ai_assisted_wrap_up_now failed: ${err instanceof Error ? err.message : String(err)}`,
          );
        }
      },
    ),
  );

  server.registerTool(
    "ai_assisted_end_session",
    {
      description:
        "Finalize the active AI-Assisted session. Computes the bundle manifest (event_count, log_hash, snapshot_count, trust_gap_count) and uploads it so the dashboard can grade the run. Returns the integrityStatus reported by the server (`bundle_uploaded`, `bundle_log_hash_mismatch`, etc.) so the host can surface it to the candidate. Idempotent — calling twice on the same session returns the second server response without re-signing.",
      inputSchema: {
        sessionId: z.string(),
      },
    },
    async (args) => {
      const state = aiAssistedSessions.get(args.sessionId);
      if (!state) {
        return asText(
          `Unknown AI-Assisted session: ${args.sessionId}. Either ai_assisted_start_session was never called or the runner restarted between start and end.`,
        );
      }
      const endedAt = new Date().toISOString();
      // Task #1193 — in-process hook capture + per-event signing log
      // were retired in 2.0.0. The bundle manifest is now a session-end
      // marker (zeros + canonical empty-log hash); the dashboard grades
      // the Cursor chat export uploaded below instead.
      const emptyHash = aiSha256Hex("");
      try {
        const result = await api.finalizeAiAssistedBundle(args.sessionId, {
          session_id: args.sessionId,
          event_count: 0,
          final_event_hash: emptyHash,
          log_hash: emptyHash,
          snapshot_count: 0,
          trust_gap_count: 0,
          ended_at: endedAt,
          runner_version: state.runnerVersion,
          adapter_version: state.adapterVersion,
        });
        const endedState = state;
        aiAssistedSessions.delete(args.sessionId);
        // Task #1144 — re-enable phase-gated AI-Assisted tools so a
        // fresh `ai_assisted_start_session` does not inherit the
        // disabled state from a prior wrap-up.
        resetGatedTools("ai_assisted");

        // Task #1176 — Cursor export auto-upload for AI-Assisted runs.
        // Same retry/queue/stderr semantics as the coached counterpart.
        try {
          const { autoUploadCursorExport } = await import(
            "./cursor-export/upload.js"
          );
          void endedState;
          const ce = await autoUploadCursorExport({
            api,
            sessionId: args.sessionId,
            source: "auto",
          });
          if (ce.status === "uploaded") {
            process.stderr.write(
              `[cursor-export] uploaded ${ce.sizeBytes ?? "?"} bytes from ${ce.sourcePath}\n`,
            );
          } else if (ce.status === "not_found") {
            process.stderr.write(
              `[cursor-export] could not locate a Cursor export — will retry on next runner start. Run \`prepsavant upload-cursor-export --session-id ${args.sessionId} --file <path>\` to upload manually.\n`,
            );
          } else {
            process.stderr.write(
              `[cursor-export] upload failed (${ce.reason ?? "unknown"}) — queued for automatic retry on next runner start.\n`,
            );
          }
        } catch (err) {
          process.stderr.write(
            `[cursor-export] auto-upload errored: ${(err as Error).message} — queued for automatic retry on next runner start.\n`,
          );
          try {
            const { enqueue } = await import(
              "./cursor-export/pending-queue.js"
            );
            enqueue({
              sessionId: args.sessionId,
              filePath: null,
              reason: `outer_error: ${(err as Error).message}`,
            });
          } catch {
            /* best-effort */
          }
        }

        return asText(
          [
            `AI-Assisted session ended.`,
            `integrity_status: ${result.integrityStatus}`,
            `event_count: 0 (per-event capture retired in 2.0.0)`,
            `snapshot_count: 0`,
            `trust_gap_count: 0`,
            `ended_at: ${endedAt}`,
          ].join("\n"),
        );
      } catch (err) {
        return asText(
          `Could not finalize AI-Assisted bundle: ${err instanceof Error ? err.message : String(err)}`,
        );
      }
    },
  );

  // task-827 — write a pid lockfile so `prepsavant install` knows a Sam
  // runner is currently active and refuses to rewrite MCP host configs
  // mid-session. The lock is best-effort: any failure (read-only home
  // dir, permission error) must not prevent the runner from starting.
  // The release callback is wired both for graceful shutdown signals and
  // through `process.on("exit")` inside `acquireRunnerLock`.
  // Skipped when an injected transport is supplied (test harness) so we
  // don't touch the user's `~/.prepsavant` from a unit test.
  if (!opts.transport) {
    try {
      const release = acquireRunnerLock();
      const onSignal = (): void => {
        release();
        process.exit(0);
      };
      process.once("SIGINT", onSignal);
      process.once("SIGTERM", onSignal);
    } catch (err) {
      process.stderr.write(
        `[prepsavant] could not write runner lockfile (continuing): ${err instanceof Error ? err.message : String(err)}\n`,
      );
    }
  }

  await server.connect(opts.transport ?? new StdioServerTransport());
  if (!opts.transport) {
    process.stderr.write(
      `[prepsavant] sam MCP server v${ADAPTER_VERSION} listening on stdio\n`,
    );
  }

  // Task #1176 — drain pending Cursor-export uploads in the background
  // so a slow retry never blocks MCP framing.
  void (async (): Promise<void> => {
    try {
      const { retryPendingUploads } = await import(
        "./cursor-export/upload.js"
      );
      const drain = await retryPendingUploads({ api });
      if (drain.retried > 0) {
        process.stderr.write(
          `[cursor-export] retried ${drain.retried} pending upload(s); ${drain.succeeded} succeeded\n`,
        );
      }
    } catch {
      /* best-effort */
    }
  })();
}

// Targeted system prompt for the research extractor. We deliberately do NOT
// reuse SAM_SYSTEM_PROMPT here — Sam's coaching voice is for users, not for a
// JSON extraction task. This keeps the model focused and the output parseable.
const SAM_RESEARCH_SYSTEM_PROMPT = `You are a careful HTML-to-JSON extractor for a job-search assistant. Your only
job is to identify open engineering / technical roles on a careers page excerpt
and return them as strict JSON. Never invent roles that are not on the page.
Never include sales, marketing, finance, recruiting, or general operations
roles. If you are uncertain, omit the role. Output JSON only — no commentary,
no markdown fences.`;

const ROLE_FAMILIES = new Set([
  "backend",
  "frontend",
  "fullstack",
  "data",
  "infra",
  "mobile",
  "ml",
  "security",
  "other",
]);

const SENIORITIES = new Set([
  "intern",
  "junior",
  "mid",
  "senior",
  "staff",
  "principal",
  "lead",
  "manager",
]);

const REMOTE_POLICIES = new Set(["remote", "hybrid", "onsite", "unspecified"]);

interface ResearchTarget {
  companyName: string;
  careersUrl: string;
  companySlug?: string;
  industry?: string;
}

interface NormalizedJob {
  companyName: string;
  companySlug?: string;
  industry?: string;
  careersUrl?: string;
  title: string;
  canonicalUrl: string;
  source: string;
  roleFamily: string;
  seniority: string;
  location: string;
  remotePolicy: string;
  postingExcerpt: string;
  team?: string;
}

function pickEnum(
  value: unknown,
  allowed: Set<string>,
  fallback: string,
): string {
  if (typeof value !== "string") return fallback;
  const v = value.trim().toLowerCase();
  return allowed.has(v) ? v : fallback;
}

function asString(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const t = value.trim();
  return t ? t : undefined;
}

function absolutize(url: string | undefined, base: string): string | null {
  if (!url) return null;
  try {
    return new URL(url, base).toString();
  } catch {
    return null;
  }
}

function normalizeExtractedJob(
  raw: unknown,
  target: ResearchTarget,
  baseUrl: string,
  _maxJobs: number,
): NormalizedJob | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  const title = asString(r["title"]);
  if (!title) return null;
  const canonicalUrl =
    absolutize(asString(r["canonicalUrl"]) ?? asString(r["url"]), baseUrl) ??
    target.careersUrl;
  return {
    companyName: target.companyName,
    companySlug: target.companySlug,
    industry: target.industry,
    careersUrl: target.careersUrl,
    title,
    canonicalUrl,
    source: "runner",
    roleFamily: pickEnum(r["roleFamily"], ROLE_FAMILIES, "other"),
    seniority: pickEnum(r["seniority"], SENIORITIES, "mid"),
    location: asString(r["location"]) ?? "Unspecified",
    remotePolicy: pickEnum(r["remotePolicy"], REMOTE_POLICIES, "unspecified"),
    postingExcerpt:
      asString(r["postingExcerpt"]) ??
      asString(r["summary"]) ??
      `Open role at ${target.companyName}.`,
    team: asString(r["team"]),
  };
}

// Minimal, dependency-free careers-page fetch + HTML→text. Keeps the runner
// package self-contained (no jsdom / cheerio). Trims to a budget so the host
// model sees a focused excerpt rather than a huge nav/footer dump.
async function fetchCareersPage(url: string): Promise<string> {
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(), 15_000);
  try {
    const res = await fetch(url, {
      headers: {
        "user-agent": `prepsavant-runner/${ADAPTER_VERSION} (+https://prepsavant.com)`,
        accept: "text/html,application/xhtml+xml",
      },
      signal: ac.signal,
      redirect: "follow",
    });
    if (!res.ok) {
      throw new Error(`careers page returned HTTP ${res.status}`);
    }
    const html = await res.text();
    return htmlToText(html).slice(0, 12_000);
  } finally {
    clearTimeout(timer);
  }
}

// SHA-256 hex digest used as the careers-page cache key. We hash the
// already-trimmed text (not the raw HTML) so cosmetic markup churn —
// CSRF tokens, cache-busting query strings in scripts, etc. — does not
// invalidate the cache when the visible role list is identical.
function sha256Hex(input: string): string {
  return createHash("sha256").update(input).digest("hex");
}

function htmlToText(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, " ")
    .replace(/<\/(p|div|li|h[1-6]|tr|br)>/gi, "\n")
    .replace(/<br\s*\/?\s*>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&#39;/gi, "'")
    .replace(/&quot;/gi, '"')
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}
