// MCP server registering practice_* and enrich_* tools. Runs on stdio by
// default (`prepsavant mcp`). Tools call into the Sam HTTP API + the local
// sandbox; responses use MCP sampling for Sam's voice and fall back to the
// server-side voice when sampling is unavailable.
import { createHash } from "node:crypto";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { SamApi } from "./api.js";
import {
  ADAPTER_VERSION,
  readConfig,
  readLocalResearchTargets,
  type LocalResearchTarget,
} from "./config.js";
import {
  runJavascriptSandbox,
  runTypescriptSandbox,
  type SandboxResult,
} from "./sandbox/node.js";
import { runPythonSandbox } from "./sandbox/python.js";
import {
  buildJobEnrichmentGrounding,
  buildJobResearchGrounding,
  buildReviewGrounding,
  inferCompanyPattern,
} from "./persona.js";
import { PersonaCache, DIRECTIVE_FALLBACK } from "./persona-cache.js";
import type { CheckInDirective } from "./api.js";
import { sampleSamVoice, tryExtractJson } from "./sampling.js";
import {
  startCoachedSession,
  getCoachedSession,
  endCoachedSession,
  recordAiAssist,
  updateHintLevel,
} from "./coached/session.js";
import {
  buildCheckInPayload,
  isStallEscalation,
  resolveCoachedWorkDir,
} from "./coached/check-in.js";
import {
  buildCoachedPostMortemText,
  formatCoachedEndSessionResponse,
} from "./coached/post-mortem.js";
import { consumeStudyAskStream } from "./study/stream-consumer.js";

// Surfaces the runner is allowed to push back into the dashboard's enrichment
// cache. Mirrors the server-side TemplateSurface union — kept here as a
// runtime-checkable list so the `forget_dashboard_copy` tool can refuse
// unknown surfaces before round-tripping to the API.
const ENRICHMENT_SURFACES = [
  "kickoff_interview_prep",
  "kickoff_job_search",
  "why_you_fit",
  "application_angle",
  "hint_followup",
  "session_review",
] as const;
type EnrichmentSurface = (typeof ENRICHMENT_SURFACES)[number];

// Best-effort label for the host model. MCP sampling doesn't surface the
// underlying model name, so we mark it as `mcp_host` to make it obvious in
// the dashboard that the copy was generated by whatever host the user has
// (Claude Desktop, Cursor, Codex). The dashboard renders this verbatim
// after "model:".
const RUNNER_MODEL_LABEL = "mcp_host";

function asText(s: string) {
  return { content: [{ type: "text" as const, text: s }] };
}

// Append a machine-readable nextAction JSON block to tool response text.
// Hosts MUST parse and honor the `action` field:
//   - stay_quiet → do nothing proactive
//   - all others → speak `samVoiceLine` verbatim on the next turn
//   - For time_warning/wrap_up only speak once per `timeMilestone` value.
// Returns "" when action is stay_quiet (nothing to append).
function formatDirective(d: CheckInDirective | null | undefined): string {
  if (!d || d.action === "stay_quiet") return "";
  const samVoiceLine = d.samVoiceLine ?? DIRECTIVE_FALLBACK[d.action];
  const payload = {
    action: d.action,
    samVoiceLine,
    reason: d.reason,
    ...(d.timeMilestone !== undefined && d.timeMilestone !== null
      ? { timeMilestone: d.timeMilestone }
      : {}),
  };
  return `\nnextAction: ${JSON.stringify(payload)}`;
}

function summariseSandbox(r: SandboxResult): string {
  const passed = r.cases.filter((c) => c.passed).length;
  const failed = r.cases.length - passed;
  return `${r.outcome.toUpperCase()} • ${passed} passed, ${failed} failed • ${r.runtimeVersion} • ${r.durationMs}ms`;
}

export async function runMcpServer(): Promise<void> {
  const cfg = readConfig();
  if (!cfg.token) {
    // We still start the server so the host can introspect tools, but every
    // tool call surfaces a clear error pointing at `prepsavant auth`.
    process.stderr.write(
      "[prepsavant] No device token. Run `prepsavant auth` to authorize.\n",
    );
  }
  const api = new SamApi(cfg);
  const persona = new PersonaCache(api);
  // Best-effort warmup so the first tool call already has the live persona
  // composed from the server. Failure here is non-fatal; PersonaCache will
  // serve the bundled fallback prompt and retry on demand.
  if (cfg.token) {
    persona.refresh(true).catch(() => {
      // Already logged inside PersonaCache.refresh.
    });
  }

  // Helper: every Sam-voice sampling pass goes through here so all tools
  // share the same up-to-date system prompt without each one having to
  // remember to re-poll.
  const samplingSystemPrompt = async (): Promise<string> => {
    const resolved = await persona.refresh();
    return resolved.systemPrompt;
  };

  // Best-effort enrichment push. Failures are surfaced on stderr but never
  // bubble into the user-visible tool response — the runner has already done
  // its primary job (returning the generated text); the dashboard cache is a
  // nice-to-have copy. Expected 4xx responses (402 missing entitlement, 400
  // bad request from a stale surface enum) are logged at "warn" so a
  // free-tier user — or a runner that ships ahead of a server schema bump —
  // doesn't see a noisy stack trace on every coaching turn.
  const pushEnrichmentBestEffort = async (args: {
    surface: EnrichmentSurface;
    subject?: string;
    body: string;
  }): Promise<void> => {
    if (!args.body.trim()) return;
    try {
      await api.putSamEnrichment({
        surface: args.surface,
        subject: args.subject,
        body: args.body,
        modelLabel: RUNNER_MODEL_LABEL,
      });
    } catch (err) {
      const e = err as { status?: number; message?: string };
      const isExpected4xx =
        typeof e.status === "number" && e.status >= 400 && e.status < 500;
      const tag = isExpected4xx ? "warn" : "error";
      process.stderr.write(
        `[prepsavant] ${tag}: enrichment push (${args.surface}${args.subject ? `:${args.subject}` : ""}) failed: ${e.message ?? err}\n`,
      );
    }
  };

  const server = new McpServer(
    { name: "sam", version: ADAPTER_VERSION },
    { capabilities: { tools: {} } },
  );

  // ---------------------------------------------------------------------
  // practice_list_questions
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_list_questions",
    {
      description: "List interview-prep questions available for practice.",
      inputSchema: {},
    },
    async () => {
      const list = await api.listQuestions();
      const lines = list.items.map(
        (q) =>
          `${q.id}\t${q.title} [${q.roleFamily}/${q.difficulty}] (${q.languages.join(", ")})`,
      );
      return asText(lines.join("\n") || "No questions available.");
    },
  );

  // ---------------------------------------------------------------------
  // practice_start_session
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_start_session",
    {
      description:
        "DEPRECATED — use coached_start_session instead. Start a new practice session for a given question. Returns the session id and the kickoff brief.",
      inputSchema: {
        questionId: z.string(),
        companyId: z.string().optional(),
        targetDurationMinutes: z.number().int().min(5).max(180).optional(),
      },
    },
    async (args) => {
      const start = await api.startSession({
        questionId: args.questionId,
        companyId: args.companyId,
        targetDurationMinutes: args.targetDurationMinutes,
      });
      const detail = (await api.getSession(start.sessionId)) as {
        kickoffBriefVerbatim?: string;
      };
      return asText(
        [
          `session_id: ${start.sessionId}`,
          "",
          detail.kickoffBriefVerbatim ?? "(no kickoff brief)",
        ].join("\n"),
      );
    },
  );

  // ---------------------------------------------------------------------
  // practice_submit_attempt — runs the user's code in the local sandbox,
  // pushes the graded attempt, asks the host model for Sam-voice review.
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_submit_attempt",
    {
      description:
        "DEPRECATED — use practice_submit_attempt only for sessions started via practice_start_session. For new Coached sessions, submit attempts via your editor's run/test tools. Run the user's solution against the pinned tests in a local sandbox, push the graded attempt to Sam, and produce a Sam-voice review.",
      inputSchema: {
        sessionId: z.string(),
        language: z.enum(["python", "javascript", "typescript"]),
        code: z.string().min(1),
      },
    },
    async (args) => {
      // 1. Fetch the question + pinned tests for this session.
      const session = (await api.getSession(args.sessionId)) as {
        session: { questionId: string; companyName?: string };
        question: { title: string };
        attempts: { id: string; attemptNumber: number }[];
        hints: { level: number }[];
      };
      const question = await api.getQuestion(session.session.questionId);
      const tests = question.tests[args.language];
      if (!tests) {
        return asText(
          `No pinned tests for language "${args.language}" on this question.`,
        );
      }
      const timeoutMs = tests.timeoutMs ?? 5_000;

      // 2. Run sandbox.
      const sandbox =
        args.language === "python"
          ? runPythonSandbox(args.code, tests.entry, tests.cases, timeoutMs)
          : args.language === "typescript"
            ? runTypescriptSandbox(args.code, tests.entry, tests.cases, timeoutMs)
            : runJavascriptSandbox(args.code, tests.entry, tests.cases, timeoutMs);

      const passed = sandbox.cases.filter((c) => c.passed).length;
      const failed = sandbox.cases.length - passed;

      // 3. Push attempt.
      const pushed = await api.pushAttempt(args.sessionId, {
        language: args.language,
        code: args.code,
        outcome: sandbox.outcome,
        timedOut: sandbox.timedOut,
        durationMs: sandbox.durationMs,
        adapterVersion: ADAPTER_VERSION,
        runtimeVersion: sandbox.runtimeVersion,
        cases: sandbox.cases.map((c) => ({
          id: c.id,
          // Server's RunnerPushAttemptBody requires a `status` enum, not a
          // boolean. We coarsen booleans to "pass" / "fail" — sandbox runners
          // surface timeouts via the top-level `outcome`/`timedOut` already.
          status: c.passed ? ("pass" as const) : ("fail" as const),
          durationMs: c.durationMs,
          stderrExcerpt: c.stderrExcerpt,
        })),
      });

      // 4. Ask the host model for review/probe in Sam's voice.
      // Infer company pattern from the company name so Sam frames feedback
      // against what this company actually tests, not a generic root cause.
      const companyPattern = session.session.companyName
        ? inferCompanyPattern(session.session.companyName)
        : "generic";
      const grounding = buildReviewGrounding({
        questionTitle: question.question.title,
        language: args.language,
        outcome: sandbox.outcome,
        passedCount: passed,
        failedCount: failed,
        failedCases: sandbox.cases
          .filter((c) => !c.passed)
          .map((c) => ({ id: c.id, stderrExcerpt: c.stderrExcerpt })),
        attemptNumber: (session.attempts[session.attempts.length - 1]?.attemptNumber ?? 0) + 1,
        hintsTaken: session.hints.length,
        companyPattern,
      });
      const fallbackText = `${pushed.reviewVerbatim}\n\n${pushed.probeVerbatim}`;
      const sampling = await sampleSamVoice(
        server.server,
        await samplingSystemPrompt(),
        grounding,
        fallbackText,
      );

      let reviewText = pushed.reviewVerbatim;
      let probeText: string | undefined = pushed.probeVerbatim;
      let source: "runner_sampling" | "runner_fallback" = "runner_fallback";
      if (sampling.source === "runner_sampling") {
        const parsed = tryExtractJson<{ review?: string; probe?: string }>(
          sampling.text,
        );
        if (parsed?.review) {
          reviewText = parsed.review;
          probeText = parsed.probe;
          source = "runner_sampling";
        } else {
          reviewText = sampling.text;
          source = "runner_sampling";
        }
      }

      // 5. Push the final review back so the dashboard can render it.
      try {
        await api.pushReview(args.sessionId, {
          attemptId: pushed.attempt.id,
          reviewText,
          probeText,
          source,
        });
      } catch {
        // Non-fatal: the attempt is already saved with the server-side fallback.
      }

      // 6. Mirror the same review into the new surface×subject enrichment
      //    cache so the session-review surface on the dashboard renders the
      //    "Generated locally by Sam in your IDE" badge instead of the
      //    static template fallback. We only push when sampling actually
      //    succeeded — the server-side fallback is identical to what the
      //    template would render anyway.
      if (source === "runner_sampling") {
        const composed = probeText
          ? `${reviewText}\n\n${probeText}`
          : reviewText;
        await pushEnrichmentBestEffort({
          surface: "session_review",
          subject: args.sessionId,
          body: composed,
        });
      }

      return asText(
        [
          summariseSandbox(sandbox),
          "",
          reviewText,
          probeText ? `\n${probeText}` : "",
          formatDirective(pushed.nextAction),
        ]
          .filter(Boolean)
          .join("\n"),
      );
    },
  );

  // ---------------------------------------------------------------------
  // practice_request_hint
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_request_hint",
    {
      description: "DEPRECATED — use coached_ask for Coached sessions. Ask Sam for the next hint on the active session.",
      inputSchema: { sessionId: z.string() },
    },
    async (args) => {
      const hint = await api.requestHint(args.sessionId);
      const hintLine = hint.exhausted
        ? `(no more hints — level ${hint.totalLevels} reached)`
        : `Hint ${hint.level}/${hint.totalLevels}:\n${hint.hintText}`;
      const directive = formatDirective(hint.nextAction);
      return asText(directive ? `${hintLine}${directive}` : hintLine);
    },
  );

  // ---------------------------------------------------------------------
  // practice_check_in — host calls this after every message during a
  // session (or on a ~3 min timer) to get the current directive. The
  // host MUST speak samVoiceLine verbatim when action !== stay_quiet.
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_check_in",
    {
      description:
        "DEPRECATED — use coached_check_in for new Coached sessions. Check in with Sam during an active practice session. Returns a directive: stay_quiet (do nothing), probe (surface the samVoiceLine to the user verbatim), hint_offer (tell the user a hint is available), time_warning, or wrap_up.",
      inputSchema: { sessionId: z.string() },
    },
    async (args) => {
      const directive = await api.checkIn(args.sessionId);
      // Always return the full directive verbatim as JSON — strict pass-through
      // so hosts have a stable, typed contract regardless of action.
      // When action=stay_quiet the host must do nothing proactive.
      // samVoiceLine is passed as-is from the server; hosts may fall back to
      // their own phrasing if null, but the runner does not substitute here.
      const samVoiceLine = directive.samVoiceLine ?? null;
      const payload: Record<string, unknown> = {
        action: directive.action,
        samVoiceLine,
        reason: directive.reason,
      };
      if ("timeMilestone" in directive && directive.timeMilestone != null) {
        payload["timeMilestone"] = directive.timeMilestone;
      }
      return asText(JSON.stringify(payload));
    },
  );

  // ---------------------------------------------------------------------
  // practice_end_session
  // ---------------------------------------------------------------------
  server.registerTool(
    "practice_end_session",
    {
      description: "DEPRECATED — use coached_end_session for new Coached sessions. End the active practice session.",
      inputSchema: { sessionId: z.string() },
    },
    async (args) => {
      await api.endSession(args.sessionId);
      return asText("Session ended.");
    },
  );

  // =====================================================================
  // COACHED MODE TOOLS
  // These tools run the Coached session lifecycle entirely inside the user's
  // real editor + AI chat host (Cursor, Claude Desktop, Codex). Sam watches
  // the project passively and delivers nudges when the user stalls. AI usage
  // during a Coached session is detected and flagged in the recap, not blocked.
  // =====================================================================

  // ---------------------------------------------------------------------
  // coached_pick_question — browse and filter available questions from chat.
  // A user can type "give me a coached question for [role/topic]" and Sam
  // returns matching questions without opening the webapp.
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_pick_question",
    {
      description:
        "List interview-prep questions available for a Coached session, optionally filtered by role family, difficulty, or language. Returns questions the user can pick from to start a Coached session via coached_start_session.",
      inputSchema: {
        roleFamily: z
          .enum(["swe", "data", "ml", "infra", "mobile", "security", "other"])
          .optional(),
        difficulty: z.enum(["easy", "medium", "hard"]).optional(),
        language: z
          .enum(["python", "javascript", "typescript"])
          .optional(),
      },
    },
    async (args) => {
      const raw = await api.listQuestions();
      const items = raw.items.filter((q) => {
        if (args.roleFamily && q.roleFamily !== args.roleFamily) return false;
        if (args.difficulty && (q as { difficulty?: string }).difficulty !== args.difficulty) return false;
        if (args.language) {
          const langs = q.languages ?? [];
          if (!langs.includes(args.language)) return false;
        }
        return true;
      });
      if (items.length === 0) {
        return asText(
          "No questions match those filters. Try removing one of the filters or ask with no filters to see all questions.",
        );
      }
      const lines = items.map(
        (q) =>
          `${q.id}\t${q.title} [${q.roleFamily}] (${q.languages.join(", ")})`,
      );
      return asText(
        [
          `Found ${items.length} question(s). Pick one and call coached_start_session with its id.`,
          "",
          ...lines,
        ].join("\n"),
      );
    },
  );

  // ---------------------------------------------------------------------
  // coached_start_session — start a Coached session entirely from chat.
  // Delivers the question + brief into the AI chat so the user never has
  // to open the webapp. Optionally accepts workspaceDir to enable passive
  // file-system watching for stall detection.
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_start_session",
    {
      description:
        "Start a new Coached session for a given question. Delivers the question prompt and session brief into chat. The host should follow the HOST INSTRUCTIONS in the response to drive coaching nudges. Pass workDir (absolute path to the project folder) to enable stall detection via file-system watching; defaults to the runner's current working directory when omitted. `workspaceDir` is accepted as a backward-compatible alias.",
      inputSchema: {
        questionId: z.string(),
        companyId: z.string().optional(),
        targetDurationMinutes: z.number().int().min(5).max(180).optional(),
        workDir: z.string().optional(),
        // Backward-compatible alias for hosts pinned to the older field name.
        // `workDir` wins when both are present.
        workspaceDir: z.string().optional(),
      },
    },
    async (args) => {
      const start = await api.startSession({
        questionId: args.questionId,
        companyId: args.companyId,
        targetDurationMinutes: args.targetDurationMinutes,
      });
      const detail = (await api.getSession(start.sessionId)) as {
        question?: { title?: string; prompt?: string };
        kickoffBriefVerbatim?: string;
      };

      const questionTitle = detail.question?.title ?? "Interview question";
      const questionPrompt = detail.question?.prompt ?? "";

      startCoachedSession({
        sessionId: start.sessionId,
        questionId: args.questionId,
        questionTitle,
        questionPrompt,
        workspaceDir: resolveCoachedWorkDir(args),
      });

      const brief = [
        `session_id: ${start.sessionId}`,
        "",
        `# ${questionTitle}`,
        "",
        questionPrompt,
        "",
        "---",
        "",
        "HOST INSTRUCTIONS (Coached mode — follow exactly):",
        "1. Call coached_check_in after every user message and at least every 3 minutes.",
        "2. coached_check_in returns a directive. When action is not \"stay_quiet\", speak samVoiceLine verbatim.",
        "3. If YOU generate, edit, or refactor code for the user — not as a coaching nudge but as direct assistance — call coached_check_in with aiAssistDetected:true and a brief aiAssistSummary describing what you did. This is detection only; the session continues.",
        "4. Do NOT give the user a direct solution unless they explicitly ask Sam to switch to explanation mode.",
        "5. When the user ends the session or says they are done, call coached_end_session.",
        args.targetDurationMinutes
          ? `6. This is a timed session: ${args.targetDurationMinutes} minutes.`
          : "",
      ]
        .filter(Boolean)
        .join("\n");

      return asText(brief);
    },
  );

  // ---------------------------------------------------------------------
  // coached_ask — clarifying questions about the problem, answered by Sam
  // in the study/coach persona. Available at any time during a Coached
  // session. Sam answers without giving away the solution.
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_ask",
    {
      description:
        "Ask Sam a clarifying question about the current Coached session's problem. Sam answers in the coaching persona — explains concepts, gives hints when prompted, but does not hand over a full solution unprompted. Pass the sessionId so Sam can scope the answer to the right problem.",
      inputSchema: {
        sessionId: z.string(),
        question: z.string().min(1),
      },
    },
    async (args) => {
      const state = getCoachedSession(args.sessionId);
      let questionContext = "";
      if (state) {
        questionContext = `\n\nProblem being coached:\nTitle: ${state.questionTitle}\n\n${state.questionPrompt}`;
      } else {
        try {
          const detail = (await api.getSession(args.sessionId)) as {
            question?: { title?: string; prompt?: string };
          };
          if (detail.question) {
            questionContext = `\n\nProblem being coached:\nTitle: ${detail.question.title ?? ""}\n\n${detail.question.prompt ?? ""}`;
          }
        } catch {
        }
      }

      const systemPrompt = await samplingSystemPrompt();
      const userPrompt = [
        `The user is in a Coached session and has a clarifying question about the problem. Answer it in Sam's coaching persona — explain concepts freely, give hints when explicitly requested, but do not hand over a full working solution unless the user explicitly asks to switch to explanation mode.`,
        questionContext,
        `\nUser's question: ${args.question}`,
      ].join("");

      const sampling = await sampleSamVoice(
        server.server,
        systemPrompt,
        userPrompt,
        "I can't answer that right now. Try rephrasing or ask in the webapp.",
      );
      return asText(sampling.text);
    },
  );

  // ---------------------------------------------------------------------
  // coached_check_in — periodic heartbeat during a Coached session.
  // Returns a directive telling the host whether to stay quiet, offer a
  // hint, probe the user, or issue a time warning. Also accepts AI-assist
  // reports from the host so the runner can accumulate and persist them.
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_check_in",
    {
      description:
        "Check in with Sam during an active Coached session. Returns a directive: stay_quiet, probe, hint_offer, time_warning, or wrap_up. Call this after every user message and on a ~3 min heartbeat. If you (the host) generated or edited code on the user's behalf, set aiAssistDetected:true and describe what you did in aiAssistSummary.",
      inputSchema: {
        sessionId: z.string(),
        aiAssistDetected: z.boolean().optional(),
        aiAssistSummary: z.string().optional(),
      },
    },
    async (args) => {
      // Each call to coached_check_in with aiAssistDetected:true represents
      // exactly one AI-assist event. We always post delta=1 so the server-side
      // counter increments correctly regardless of how many prior events have
      // been accumulated locally.
      if (args.aiAssistDetected) {
        recordAiAssist(args.sessionId, args.aiAssistSummary ?? "");
        await api.pushCoachedAiAssist(args.sessionId, {
          count: 1,
          summary: args.aiAssistSummary,
        }).catch(() => {});
      }

      const directive = await api.checkIn(args.sessionId);
      const state = getCoachedSession(args.sessionId);
      // Detect runner-driven stall escalation BEFORE building the payload
      // (buildCheckInPayload returns the post-escalation directive). If the
      // server said `stay_quiet` and we upgraded it because the user has
      // stopped editing files, report a stall_nudge event back to the API
      // so the post-mortem can surface how often Sam had to break the
      // silence (Task #564). Best-effort — we never block the directive
      // delivery on the network call.
      if (isStallEscalation(directive, state)) {
        await api.pushCoachedStallNudge(args.sessionId, { count: 1 }).catch(() => {});
      }
      const payload = buildCheckInPayload(directive, state);
      return asText(JSON.stringify(payload));
    },
  );

  // ---------------------------------------------------------------------
  // coached_end_session — end session + deliver in-chat post-mortem.
  // Sam walks through what happened: score, what was hit/missed, and
  // an explicit offer to continue the debrief via coached_ask.
  // ---------------------------------------------------------------------
  server.registerTool(
    "coached_end_session",
    {
      description:
        "End the active Coached session and receive an in-chat post-mortem from Sam: score summary, what was hit or missed, AI assistance flag (if any), and an invitation to ask follow-up questions via coached_ask.",
      inputSchema: { sessionId: z.string() },
    },
    async (args) => {
      const state = endCoachedSession(args.sessionId);

      // End the session first so the server-side row reflects the final
      // status before we fetch detail. The detail call is the
      // authoritative source of truth for AI-assist counts (they're
      // posted via /coached-events from outside the runner's in-memory
      // state, e.g. by host-side hooks).
      await api.endSession(args.sessionId).catch(() => {});

      let detail: {
        session?: {
          attemptsTotal?: number;
          hintsUsed?: number;
          passedLatest?: boolean;
          coachedAiAssistDetected?: boolean;
          coachedAiAssistCount?: number;
          coachedStallNudgeCount?: number;
        };
        question?: { title?: string };
        attempts?: Array<{ outcome?: string }>;
        hints?: Array<unknown>;
      } = {};
      try {
        detail = (await api.getSession(args.sessionId)) as typeof detail;
      } catch {
      }

      // Prefer server-authoritative AI-assist counts; fall back to the
      // runner's in-memory state if the detail fetch failed.
      const serverAiAssistCount = detail.session?.coachedAiAssistCount;
      const serverAiAssistDetected = detail.session?.coachedAiAssistDetected;
      const inMemoryAiAssistCount = state?.aiAssistCount ?? 0;
      const aiAssistCount =
        typeof serverAiAssistCount === "number"
          ? serverAiAssistCount
          : inMemoryAiAssistCount;
      const aiAssistDetected =
        typeof serverAiAssistDetected === "boolean"
          ? serverAiAssistDetected
          : inMemoryAiAssistCount > 0;
      const aiAssistSummaries = state?.aiAssistSummaries ?? [];
      const questionTitle =
        detail.question?.title ?? state?.questionTitle ?? "the problem";
      const attemptsTotal = detail.session?.attemptsTotal ?? detail.attempts?.length ?? 0;
      const hintsUsed = detail.session?.hintsUsed ?? detail.hints?.length ?? 0;
      const passedLatest = detail.session?.passedLatest;
      // Stall-nudge counts only live server-side (Task #564) — the runner
      // doesn't keep an in-memory accumulator. If the detail fetch failed,
      // fall back to 0 rather than fabricating a value.
      const stallNudgeCount = detail.session?.coachedStallNudgeCount ?? 0;

      const postMortem = buildCoachedPostMortemText({
        questionTitle,
        attemptsTotal,
        hintsUsed,
        passedLatest,
        aiAssistDetected,
        aiAssistCount,
        aiAssistSummaries,
        stallNudgeCount,
      });

      return asText(
        formatCoachedEndSessionResponse({
          session_id: args.sessionId,
          status: "ended",
          coachedAiAssistDetected: aiAssistDetected,
          coachedAiAssistCount: aiAssistCount,
          coachedStallNudgeCount: stallNudgeCount,
          postMortem,
        }),
      );
    },
  );

  // ---------------------------------------------------------------------
  // Study mode tools (task-531)
  //
  // These tools let the host model run a teaching chat with Sam scoped to
  // a single problem. Conversations are persisted into the existing
  // study_conversations / study_conversation_messages tables — the same
  // ones the dashboard's Study chat viewer reads from. Critically, the
  // study path NEVER writes to sessions / attempts / hint_events: this is
  // a learning surface only and must not inflate practice counters.
  //
  // Flow:
  //   1) Host calls study_start with a questionId (optionally postSessionId
  //      for a post-session reflection). Tool creates the conversation
  //      server-side and returns a kickoff brief that includes the problem
  //      prompt + the verbatim Sam study persona + handoff instructions
  //      for the host model.
  //   2) Host generates Sam's reply locally for each user turn, then
  //      calls study_send_message with both the user message and Sam's
  //      reply. The runner persists both turns.
  //   3) Host can call study_get_history to read back the transcript.
  // ---------------------------------------------------------------------

  // Inline persona builder shared with the server-side cookie path so the
  // host model receives the exact same study persona the webapp would use.
  function buildStudyPersonaPrompt(args: {
    question: {
      id: string;
      title: string;
      prompt: string;
      difficulty: string;
      estimatedMinutes: number;
    };
    mode: "study" | "post_session";
  }): string {
    const { question, mode } = args;
    const teachingRules = [
      `You are Sam — a senior interview coach in teaching mode.`,
      `The user is studying one problem and can ask anything about it.`,
      ``,
      `Tone:`,
      `- Short paragraphs. Concrete examples. No emoji. No flattery.`,
      ``,
      `Teaching-mode rules:`,
      `- Stay scoped to "${question.title}". Do not drift into general career advice or other problems.`,
      `- Explain concepts, patterns, canonical approaches, and tradeoffs freely — this is NOT a proctored session.`,
      `- Do not dump a full worked solution unprompted. If asked directly for a solution, give it.`,
      `- Do not reveal hidden test cases verbatim. You may describe what kinds of inputs are covered.`,
      `- If the user pastes code, read it and give specific feedback. Do not invent behavior the code doesn't have.`,
      `- Prefer ending each reply with one focused question to guide the user's thinking.`,
    ].join("\n");

    const problemContext = [
      ``,
      `Current problem:`,
      `Title: ${question.title}`,
      `Difficulty: ${question.difficulty}`,
      `Estimated time: ${question.estimatedMinutes} minutes`,
      ``,
      `Problem prompt:`,
      question.prompt,
    ].join("\n");

    const modeNote =
      mode === "post_session"
        ? `\n\nThis is a post-session reflection. The user just finished a graded session on this problem. The opening message (already in the transcript) summarized that session. Continue from there.`
        : ``;

    return teachingRules + problemContext + modeNote;
  }

  server.registerTool(
    "study_start",
    {
      description:
        "Open a study (teaching) conversation with Sam scoped to one problem. Pass a questionId for a fresh study chat, or postSessionId (with the same questionId) for a post-session reflection. Returns a conversationId and the kickoff brief: persona/system rules + the problem prompt the host model should follow when replying as Sam. Study chats are persisted but never create graded sessions, attempts, or hints.",
      inputSchema: {
        questionId: z.string().min(1),
        postSessionId: z.string().min(1).optional(),
      },
    },
    async (args) => {
      const mode: "study" | "post_session" = args.postSessionId
        ? "post_session"
        : "study";
      let detail;
      try {
        detail = await api.createStudyConversation({
          questionId: args.questionId,
          mode,
          ...(args.postSessionId ? { sessionId: args.postSessionId } : {}),
        });
      } catch (err) {
        return asText(
          `Could not open study conversation: ${(err as Error).message}`,
        );
      }
      const personaPrompt = buildStudyPersonaPrompt({
        question: detail.question,
        mode: detail.mode,
      });
      const opener =
        detail.messages.length > 0
          ? `\n\nOpening message already in the transcript (Sam):\n${detail.messages[detail.messages.length - 1]!.body}`
          : "";
      const kickoffBrief = [
        `conversation_id: ${detail.id}`,
        `mode: ${detail.mode}`,
        `question_id: ${detail.questionId}`,
        ``,
        `--- Study persona (only used if you fall back to study_send_message) ---`,
        personaPrompt,
        opener,
        ``,
        `--- Handoff to host ---`,
        `Preferred: after each user turn, call study_ask with conversationId="${detail.id}" and userMessage=<the user's text>. The runner streams Sam's real reply from prepsavant.com (matching the web Sam) and persists both the user turn and Sam's full reply on the server. Show the returned text to the user verbatim.`,
        `Fallback: if you cannot use study_ask, generate Sam's reply locally using the persona above and call study_send_message with the user message and your Sam reply so both turns are persisted.`,
        `Do not mix the two for the same turn — that would double-persist the user message.`,
        `Do not call study_start again for this question/session unless the user explicitly wants a new conversation.`,
      ].join("\n");
      return asText(kickoffBrief);
    },
  );

  // ---------------------------------------------------------------------
  // study_ask (task-555) — preferred path for IDE study turns.
  //
  // Streams Sam's reply from prepsavant.com so the IDE chat sees Sam's
  // actual model output (matching the web Sam experience), not whatever
  // the host AI would have improvised. The runner calls the streaming
  // server endpoint, accumulates deltas, optionally forwards them to the
  // host as `notifications/message` so progressive UIs can render them,
  // and returns the full Sam reply as the tool's text result.
  //
  // The server persists BOTH the user message and Sam's full reply into
  // study_conversation_messages, so the host MUST NOT also call
  // study_send_message after study_ask — that would double-write the user
  // turn. study_send_message remains for hosts that want to drive Sam
  // entirely from the local model.
  // ---------------------------------------------------------------------
  server.registerTool(
    "study_ask",
    {
      description:
        "Ask Sam in an open study conversation and stream his real reply from prepsavant.com. Persists both the user turn and Sam's full generated reply into the conversation transcript on the server — DO NOT also call study_send_message for the same turn. Returns Sam's full reply text. The runner forwards streamed chunks as MCP notifications/message events so chat UIs that render them can show Sam's voice live as it lands.",
      inputSchema: {
        conversationId: z.string().min(1),
        userMessage: z.string().min(1).max(8000),
      },
    },
    async (args, extra) => {
      // Best-effort notification helper. Silently ignore send failures —
      // the typing indicator and live deltas are progressive niceties;
      // the final tool text always carries the full reply.
      const notify = async (data: Record<string, unknown>): Promise<void> => {
        if (!extra?.sendNotification) return;
        try {
          await extra.sendNotification({
            method: "notifications/message",
            params: {
              level: "info",
              logger: "study_ask",
              data: { conversationId: args.conversationId, ...data },
            },
          });
        } catch {
          /* noop */
        }
      };
      let full = "";
      let errored: string | null = null;
      try {
        const result = await consumeStudyAskStream(
          api.streamStudyMessage(args.conversationId, {
            body: args.userMessage,
          }),
          notify,
        );
        full = result.full;
        errored = result.error;
      } catch (err) {
        errored = err instanceof Error ? err.message : String(err);
      }

      if (errored && !full) {
        return asText(`Could not generate Sam's reply: ${errored}`);
      }
      if (errored) {
        // Partial reply: return what we got with a footer so the host can
        // see generation didn't finish cleanly.
        return asText(`${full}\n\n(stream ended early: ${errored})`);
      }
      return asText(full);
    },
  );

  // ---------------------------------------------------------------------
  // study_retry (task-571) — recover when a previous study_ask was
  // interrupted (model error or stream disconnect after the user turn
  // landed on the server). Re-runs Sam against the trailing user turn
  // already persisted in the conversation, so the user does not have to
  // re-type their question and the transcript does not gain a duplicate
  // user message.
  // ---------------------------------------------------------------------
  server.registerTool(
    "study_retry",
    {
      description:
        "Retry Sam's reply for the trailing (unanswered) user turn of a study conversation when a previous study_ask call returned an error or was interrupted mid-stream. Does NOT insert a new user message — the user's last question is already saved on the server. Returns Sam's full reply text. Refuses if the last message in the conversation is already from Sam (nothing to recover).",
      inputSchema: {
        conversationId: z.string().min(1),
      },
    },
    async (args, extra) => {
      let full = "";
      let errored: string | null = null;
      try {
        for await (const evt of api.retryStudyMessage(args.conversationId)) {
          if (evt.type === "delta") {
            full += evt.text;
            if (extra?.sendNotification) {
              try {
                await extra.sendNotification({
                  method: "notifications/message",
                  params: {
                    level: "info",
                    logger: "study_retry",
                    data: {
                      conversationId: args.conversationId,
                      delta: evt.text,
                    },
                  },
                });
              } catch {
                /* noop */
              }
            }
          } else if (evt.type === "error") {
            errored = evt.error;
            break;
          }
        }
      } catch (err) {
        errored = err instanceof Error ? err.message : String(err);
      }

      if (errored && !full) {
        return asText(`Could not retry Sam's reply: ${errored}`);
      }
      if (errored) {
        return asText(`${full}\n\n(stream ended early: ${errored})`);
      }
      return asText(full);
    },
  );

  server.registerTool(
    "study_send_message",
    {
      description:
        "Persist one turn of a study conversation when you (the host) have already generated Sam's reply locally. Prefer study_ask, which streams Sam's real reply from prepsavant.com. Use study_send_message only when the host model is intentionally driving Sam itself. Both messages are appended in order: user first, then sam. Returns the persisted message ids and createdAt timestamps.",
      inputSchema: {
        conversationId: z.string().min(1),
        userMessage: z.string().min(1).max(8000),
        samReply: z.string().min(1).max(8000),
      },
    },
    async (args) => {
      try {
        const userMsg = await api.appendStudyMessage(args.conversationId, {
          role: "user",
          body: args.userMessage,
        });
        const samMsg = await api.appendStudyMessage(args.conversationId, {
          role: "sam",
          body: args.samReply,
        });
        return asText(
          [
            `conversation_id: ${args.conversationId}`,
            `persisted: 2 messages`,
            `user_message_id: ${userMsg.message.id} (${userMsg.message.createdAt})`,
            `sam_message_id:  ${samMsg.message.id} (${samMsg.message.createdAt})`,
          ].join("\n"),
        );
      } catch (err) {
        return asText(
          `Could not persist study turn: ${(err as Error).message}`,
        );
      }
    },
  );

  server.registerTool(
    "study_get_history",
    {
      description:
        "Read back the full transcript of a study conversation: all user and Sam messages in chronological order, plus the problem context. Use this to refresh context after the host's chat scrollback has been truncated.",
      inputSchema: {
        conversationId: z.string().min(1),
      },
    },
    async (args) => {
      let detail;
      try {
        detail = await api.getStudyConversation(args.conversationId);
      } catch (err) {
        return asText(
          `Could not load study conversation: ${(err as Error).message}`,
        );
      }
      const transcript =
        detail.messages.length === 0
          ? "(no messages yet)"
          : detail.messages
              .map(
                (m) =>
                  `[${m.createdAt}] ${m.role === "sam" ? "Sam" : "User"}: ${m.body}`,
              )
              .join("\n\n");
      return asText(
        [
          `conversation_id: ${detail.id}`,
          `mode: ${detail.mode}`,
          `question: ${detail.question.title} (${detail.question.id})`,
          ``,
          `--- Transcript (${detail.messages.length} messages) ---`,
          transcript,
        ].join("\n"),
      );
    },
  );

  // ---------------------------------------------------------------------
  // enrich_job — push why-fit + application-angle for a job.
  // ---------------------------------------------------------------------
  server.registerTool(
    "enrich_job",
    {
      description:
        "Generate Sam-voice why-fit and application-angle text for a job and push them back to the Sam dashboard. Pass calibration fields when available — they let Sam apply the Search spec's 5-dimension fit-score reasoning and name concrete risks.",
      inputSchema: {
        jobId: z.string(),
        jobTitle: z.string(),
        company: z.string(),
        jobDescription: z.string().optional(),
        candidateProfileSummary: z.string(),
        // Structured calibration fields from the candidate's profile.
        // All optional: Sam degrades gracefully when they are absent.
        currentProofPoints: z.array(z.string()).optional(),
        weakSpots: z.array(z.string()).optional(),
        calibratedTargetIndustries: z.array(z.string()).optional(),
        compFloor: z.number().optional(),
        sponsorshipNeed: z.boolean().optional(),
        geoPreference: z.string().optional(),
      },
    },
    async (args) => {
      const grounding = buildJobEnrichmentGrounding({
        jobTitle: args.jobTitle,
        company: args.company,
        jobDescription: args.jobDescription,
        candidateProfileSummary: args.candidateProfileSummary,
        currentProofPoints: args.currentProofPoints,
        weakSpots: args.weakSpots,
        calibratedTargetIndustries: args.calibratedTargetIndustries,
        compFloor: args.compFloor,
        sponsorshipNeed: args.sponsorshipNeed,
        geoPreference: args.geoPreference,
      });
      const sampling = await sampleSamVoice(
        server.server,
        await samplingSystemPrompt(),
        grounding,
        "",
      );
      let whyYouFit = "";
      let applicationAngle = "";
      let risks: string[] = [];
      let firstActionAngle = "";
      let source: "runner_sampling" | "runner_fallback" = "runner_fallback";
      if (sampling.source === "runner_sampling") {
        const parsed = tryExtractJson<{
          why_you_fit?: string;
          application_angle?: string;
          risks?: string[];
          first_action_angle?: string;
        }>(sampling.text);
        whyYouFit = parsed?.why_you_fit ?? sampling.text;
        applicationAngle = parsed?.application_angle ?? "";
        risks = parsed?.risks ?? [];
        firstActionAngle = parsed?.first_action_angle ?? "";
        source = "runner_sampling";
      }
      if (!whyYouFit) {
        return asText(
          "Sam could not generate enrichment locally (host refused sampling and no fallback was provided). Try again from the dashboard.",
        );
      }
      try {
        await api.pushJobEnrichment(args.jobId, {
          whyYouFit,
          applicationAngle,
          source,
        });
      } catch (err) {
        return asText(`Generated text but could not push it: ${(err as Error).message}`);
      }
      // Mirror into the new surface×subject enrichment cache so the
      // dashboard's why-you-fit / application-angle cards flip to the
      // "Generated locally by Sam in your IDE" state. Keep this best-effort
      // — if the user is on a free tier we still want the legacy
      // pushJobEnrichment above to record the result.
      await pushEnrichmentBestEffort({
        surface: "why_you_fit",
        subject: args.jobId,
        body: whyYouFit,
      });
      if (applicationAngle.trim()) {
        await pushEnrichmentBestEffort({
          surface: "application_angle",
          subject: args.jobId,
          body: applicationAngle,
        });
      }
      const outputParts = ["why_you_fit:", whyYouFit, "", "application_angle:", applicationAngle];
      if (firstActionAngle.trim()) {
        outputParts.push("", "first_action:", firstActionAngle);
      }
      if (risks.length > 0) {
        outputParts.push("", "risks:", ...risks.map((r) => `- ${r}`));
      }
      return asText(
        outputParts.join("\n"),
      );
    },
  );

  // ---------------------------------------------------------------------
  // enrich_shortlist — push a one-line annotation onto a shortlist item.
  // ---------------------------------------------------------------------
  server.registerTool(
    "enrich_shortlist",
    {
      description: "Push a Sam-voice annotation onto a shortlist item.",
      inputSchema: {
        shortlistItemId: z.string(),
        prompt: z.string(),
      },
    },
    async (args) => {
      const sampling = await sampleSamVoice(
        server.server,
        await samplingSystemPrompt(),
        args.prompt,
        "",
      );
      if (!sampling.text) {
        return asText("Host refused sampling and no fallback was supplied.");
      }
      try {
        await api.pushShortlistAnnotation(args.shortlistItemId, {
          annotation: sampling.text,
          source: sampling.source,
        });
      } catch (err) {
        return asText(`Generated text but could not push it: ${(err as Error).message}`);
      }
      return asText(sampling.text);
    },
  );

  // ---------------------------------------------------------------------
  // forget_dashboard_copy — clear a previously pushed enrichment row so the
  // dashboard stops showing the locally generated copy and falls back to the
  // server-side template. Useful when the user says "Sam, forget what you
  // said about job X" or when a job's underlying posting changes and the
  // generated copy is no longer accurate.
  // ---------------------------------------------------------------------
  server.registerTool(
    "forget_dashboard_copy",
    {
      description:
        "Forget a previously pushed Sam enrichment for a given surface (and optional subject id) so the dashboard reverts to the template fallback.",
      inputSchema: {
        surface: z.enum(ENRICHMENT_SURFACES),
        subject: z.string().optional(),
      },
    },
    async (args) => {
      // The server's DELETE /sam/enrichment is idempotent — it returns
      // { ok: true } whether or not a matching row existed — so we don't try
      // to distinguish "deleted" from "nothing to delete" in the response.
      try {
        await api.deleteSamEnrichment({
          surface: args.surface,
          subject: args.subject,
        });
        return asText(
          `Forgot ${args.surface}${args.subject ? `:${args.subject}` : ""}.`,
        );
      } catch (err) {
        return asText(
          `Could not forget ${args.surface}: ${(err as Error).message}`,
        );
      }
    },
  );

  // ---------------------------------------------------------------------
  // research_jobs — scan configured target companies' careers pages and
  // push the extracted openings back into the Sam dashboard so they stop
  // appearing as "sample" jobs.
  // ---------------------------------------------------------------------
  server.registerTool(
    "research_jobs",
    {
      description:
        "Scan configured target companies' careers pages and push the openings back to the Sam dashboard. Newly recorded jobs appear in shortlists without the Sample badge. When `targets` is omitted the runner falls back to the local file ~/.prepsavant/research-targets.json and then to the user's saved list on the dashboard. Re-fetched pages whose content hash matches the previous run within the freshness window are skipped to save host-model tokens; pass `force: true` to bypass the cache.",
      inputSchema: {
        targets: z
          .array(
            z.object({
              companyName: z.string(),
              careersUrl: z.string().url(),
              companySlug: z.string().optional(),
              industry: z.string().optional(),
            }),
          )
          .min(1)
          .optional(),
        maxJobsPerCompany: z.number().int().min(1).max(50).optional(),
        notes: z.string().optional(),
        // Bypass the careers-page content-hash cache and force a fresh
        // model extraction for every target.
        force: z.boolean().optional(),
        // Override the default freshness window (in hours). When the
        // cached fetch is younger than this and the hash matches, the
        // model call is skipped. Defaults to 6h.
        cacheTtlHours: z.number().int().min(0).max(168).optional(),
      },
    },
    async (args) => {
      const maxJobs = args.maxJobsPerCompany ?? 20;
      const force = args.force === true;
      const cacheTtlMs = (args.cacheTtlHours ?? 6) * 60 * 60 * 1000;
      const summary: string[] = [];

      // Resolve target list. Order:
      //   1. Explicit `targets` argument (one-off scan).
      //   2. ~/.prepsavant/research-targets.json (per-machine override).
      //   3. GET /api/jobs/research/targets (saved on the dashboard).
      // We expose where the list came from in the summary so users
      // understand why a "no targets argument" call still scanned 5 sites.
      let targets: LocalResearchTarget[] = [];
      let source: "argument" | "local_file" | "saved" = "argument";
      if (args.targets && args.targets.length > 0) {
        targets = args.targets.map((t) => ({
          companyName: t.companyName,
          careersUrl: t.careersUrl,
          companySlug: t.companySlug,
          industry: t.industry,
        }));
        source = "argument";
      } else {
        const local = readLocalResearchTargets();
        if (local && local.length > 0) {
          targets = local;
          source = "local_file";
        } else {
          try {
            const saved = await api.listResearchTargets();
            targets = saved.targets.map((t) => ({
              companyName: t.companyName,
              careersUrl: t.careersUrl,
              companySlug: t.slug,
              industry: t.industry,
            }));
            source = "saved";
          } catch (err) {
            return asText(
              `No targets supplied and could not load saved targets: ${(err as Error).message}`,
            );
          }
        }
      }

      if (targets.length === 0) {
        return asText(
          'No targets to scan. Pass `targets: [{ companyName, careersUrl }, ...]`, drop a JSON file at ~/.prepsavant/research-targets.json, or save a list at /dashboard/job-search/targets.',
        );
      }

      let run: Awaited<ReturnType<typeof api.startResearchRun>>;
      try {
        run = await api.startResearchRun({
          runnerVersion: ADAPTER_VERSION,
          modelHint: "host_sampling",
          notes: args.notes,
        });
      } catch (err) {
        return asText(
          `Could not open a research run: ${(err as Error).message}`,
        );
      }
      summary.push(`run_id: ${run.id}`);
      summary.push(`targets_source: ${source} (${targets.length} companies)`);

      let totalAdded = 0;
      let totalUpdated = 0;
      let totalSkipped = 0;
      let totalUnchanged = 0;
      let companiesAttempted = 0;
      let companiesSucceeded = 0;
      const errors: string[] = [];

      for (let i = 0; i < targets.length; i++) {
        const target = targets[i]!;
        const isLast = i === targets.length - 1;
        companiesAttempted += 1;
        // Every record call carries an explicit `company` descriptor so
        // /admin/research can show a per-company outcome row even when the
        // jobs[] payload is empty (refusal / fetch-error path).
        const companyDescriptor = {
          name: target.companyName,
          slug: target.companySlug,
          careersUrl: target.careersUrl,
        };
        // Build the per-iteration record body so error/refusal branches still
        // count this company toward `companiesScanned` on the server side
        // (the API counts unique slugs in the `jobs[]` it sees). When the
        // body is empty we can't bump that counter, so we fall back to
        // surfacing the attempt via `errorText` instead.
        let recordBody: Parameters<typeof api.recordResearchResult>[1] = {
          jobs: [],
          company: companyDescriptor,
          complete: isLast,
        };
        let outcomeLine = "";
        let errorLine: string | null = null;

        try {
          const page = await fetchCareersPage(target.careersUrl);
          const contentHash = sha256Hex(page);

          // Cache short-circuit: when the freshly-hashed page matches the
          // last successful extract for this (owner, careersUrl) AND the
          // cached fetch is still inside the freshness window, we skip the
          // host-model call entirely. The server-side accounting bumps a
          // dedicated `companiesUnchanged` counter so /admin/research can
          // tell this apart from real fetch/sampling errors.
          let cacheHit = false;
          if (!force) {
            try {
              const cached = await api.getResearchCache(target.careersUrl);
              if (
                cached &&
                cached.contentHash === contentHash &&
                Date.now() - new Date(cached.fetchedAt).getTime() < cacheTtlMs
              ) {
                cacheHit = true;
              }
            } catch {
              // Cache lookup failures are non-fatal; fall through to a
              // normal extraction. The server will recover next time.
            }
          }

          if (cacheHit) {
            recordBody = {
              jobs: [],
              company: companyDescriptor,
              complete: isLast,
              careersUrl: target.careersUrl,
              companyName: target.companyName,
              contentHash,
              skipReason: "unchanged",
            };
            outcomeLine = `${target.companyName}: unchanged since last run — skipped model call`;
          } else {
            const grounding = buildJobResearchGrounding({
              companyName: target.companyName,
              careersUrl: target.careersUrl,
              pageExcerpt: page,
              maxJobs,
            });
            const sampling = await sampleSamVoice(
              server.server,
              SAM_RESEARCH_SYSTEM_PROMPT,
              grounding,
              "",
            );

            if (sampling.source !== "runner_sampling" || !sampling.text) {
              errorLine = `${target.companyName}: host refused sampling — skipped.`;
              recordBody = {
                jobs: [],
                company: companyDescriptor,
                complete: isLast,
                careersUrl: target.careersUrl,
                companyName: target.companyName,
                skipReason: "error",
                errorText: `host_refused_sampling: ${target.companyName}`,
              };
            } else {
              const parsed = tryExtractJson<{ jobs?: unknown[] }>(sampling.text);
              const rawJobs = Array.isArray(parsed?.jobs) ? parsed!.jobs : [];
              const jobs = rawJobs
                .map((j) =>
                  normalizeExtractedJob(j, target, target.careersUrl, maxJobs),
                )
                .filter(
                  (j): j is NonNullable<ReturnType<typeof normalizeExtractedJob>> =>
                    j !== null,
                )
                .slice(0, maxJobs);
              recordBody = {
                jobs,
                company: companyDescriptor,
                complete: isLast,
                careersUrl: target.careersUrl,
                companyName: target.companyName,
                contentHash,
              };
            }
          }
        } catch (err) {
          errorLine = `${target.companyName}: ${(err as Error).message}`;
          recordBody = {
            jobs: [],
            company: companyDescriptor,
            complete: isLast,
            careersUrl: target.careersUrl,
            companyName: target.companyName,
            skipReason: "error",
            errorText: `${target.companyName}: ${(err as Error).message}`,
          };
        }

        // Always record the per-company outcome so the run's accounting and
        // completion flag stay consistent, even on refusal/fetch failure.
        let recordSucceeded = false;
        try {
          const recorded = await api.recordResearchResult(run.id, recordBody);
          recordSucceeded = true;
          totalAdded += recorded.added;
          totalUpdated += recorded.updated;
          totalSkipped += recorded.skipped;
          if (recordBody.skipReason === "unchanged") {
            totalUnchanged += 1;
            companiesSucceeded += 1;
            // outcomeLine already set above; nothing to overwrite.
          } else if (errorLine === null) {
            companiesSucceeded += 1;
            outcomeLine = `${target.companyName}: +${recorded.added} new, ~${recorded.updated} updated, ${recorded.skipped} skipped`;
          }
        } catch (recordErr) {
          errorLine =
            errorLine ??
            `${target.companyName}: record failed — ${(recordErr as Error).message}`;
        }

        // Best-effort finalize: if the LAST per-company record call failed,
        // the run is left in-flight on the server. Send one explicit empty
        // close so the run flips to completed/error and doesn't show as
        // "in-flight forever" in /admin/research.
        if (isLast && !recordSucceeded) {
          try {
            await api.recordResearchResult(run.id, {
              jobs: [],
              company: companyDescriptor,
              complete: true,
              errorText: errorLine ?? "finalize_after_record_failure",
            });
          } catch {
            // Surface via summary; nothing more we can do from the runner.
          }
        }

        if (errorLine) errors.push(errorLine);
        if (outcomeLine) summary.push(outcomeLine);
      }

      summary.push("");
      const unchangedSummary =
        totalUnchanged > 0 ? `, ${totalUnchanged} unchanged (cached)` : "";
      summary.push(
        `Totals: ${totalAdded} added, ${totalUpdated} updated, ${totalSkipped} skipped${unchangedSummary} across ${companiesSucceeded}/${companiesAttempted} companies.`,
      );
      if (errors.length > 0) {
        summary.push("");
        summary.push("Issues:");
        for (const e of errors) summary.push(`  - ${e}`);
      }
      return asText(summary.join("\n"));
    },
  );

  await server.connect(new StdioServerTransport());
  process.stderr.write(
    `[prepsavant] sam MCP server v${ADAPTER_VERSION} listening on stdio\n`,
  );
}

// Targeted system prompt for the research extractor. We deliberately do NOT
// reuse SAM_SYSTEM_PROMPT here — Sam's coaching voice is for users, not for a
// JSON extraction task. This keeps the model focused and the output parseable.
const SAM_RESEARCH_SYSTEM_PROMPT = `You are a careful HTML-to-JSON extractor for a job-search assistant. Your only
job is to identify open engineering / technical roles on a careers page excerpt
and return them as strict JSON. Never invent roles that are not on the page.
Never include sales, marketing, finance, recruiting, or general operations
roles. If you are uncertain, omit the role. Output JSON only — no commentary,
no markdown fences.`;

const ROLE_FAMILIES = new Set([
  "backend",
  "frontend",
  "fullstack",
  "data",
  "infra",
  "mobile",
  "ml",
  "security",
  "other",
]);

const SENIORITIES = new Set([
  "intern",
  "junior",
  "mid",
  "senior",
  "staff",
  "principal",
  "lead",
  "manager",
]);

const REMOTE_POLICIES = new Set(["remote", "hybrid", "onsite", "unspecified"]);

interface ResearchTarget {
  companyName: string;
  careersUrl: string;
  companySlug?: string;
  industry?: string;
}

interface NormalizedJob {
  companyName: string;
  companySlug?: string;
  industry?: string;
  careersUrl?: string;
  title: string;
  canonicalUrl: string;
  source: string;
  roleFamily: string;
  seniority: string;
  location: string;
  remotePolicy: string;
  postingExcerpt: string;
  team?: string;
}

function pickEnum(
  value: unknown,
  allowed: Set<string>,
  fallback: string,
): string {
  if (typeof value !== "string") return fallback;
  const v = value.trim().toLowerCase();
  return allowed.has(v) ? v : fallback;
}

function asString(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const t = value.trim();
  return t ? t : undefined;
}

function absolutize(url: string | undefined, base: string): string | null {
  if (!url) return null;
  try {
    return new URL(url, base).toString();
  } catch {
    return null;
  }
}

function normalizeExtractedJob(
  raw: unknown,
  target: ResearchTarget,
  baseUrl: string,
  _maxJobs: number,
): NormalizedJob | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  const title = asString(r["title"]);
  if (!title) return null;
  const canonicalUrl =
    absolutize(asString(r["canonicalUrl"]) ?? asString(r["url"]), baseUrl) ??
    target.careersUrl;
  return {
    companyName: target.companyName,
    companySlug: target.companySlug,
    industry: target.industry,
    careersUrl: target.careersUrl,
    title,
    canonicalUrl,
    source: "runner",
    roleFamily: pickEnum(r["roleFamily"], ROLE_FAMILIES, "other"),
    seniority: pickEnum(r["seniority"], SENIORITIES, "mid"),
    location: asString(r["location"]) ?? "Unspecified",
    remotePolicy: pickEnum(r["remotePolicy"], REMOTE_POLICIES, "unspecified"),
    postingExcerpt:
      asString(r["postingExcerpt"]) ??
      asString(r["summary"]) ??
      `Open role at ${target.companyName}.`,
    team: asString(r["team"]),
  };
}

// Minimal, dependency-free careers-page fetch + HTML→text. Keeps the runner
// package self-contained (no jsdom / cheerio). Trims to a budget so the host
// model sees a focused excerpt rather than a huge nav/footer dump.
async function fetchCareersPage(url: string): Promise<string> {
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(), 15_000);
  try {
    const res = await fetch(url, {
      headers: {
        "user-agent": `prepsavant-runner/${ADAPTER_VERSION} (+https://prepsavant.com)`,
        accept: "text/html,application/xhtml+xml",
      },
      signal: ac.signal,
      redirect: "follow",
    });
    if (!res.ok) {
      throw new Error(`careers page returned HTTP ${res.status}`);
    }
    const html = await res.text();
    return htmlToText(html).slice(0, 12_000);
  } finally {
    clearTimeout(timer);
  }
}

// SHA-256 hex digest used as the careers-page cache key. We hash the
// already-trimmed text (not the raw HTML) so cosmetic markup churn —
// CSRF tokens, cache-busting query strings in scripts, etc. — does not
// invalidate the cache when the visible role list is identical.
function sha256Hex(input: string): string {
  return createHash("sha256").update(input).digest("hex");
}

function htmlToText(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, " ")
    .replace(/<\/(p|div|li|h[1-6]|tr|br)>/gi, "\n")
    .replace(/<br\s*\/?\s*>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&#39;/gi, "'")
    .replace(/&quot;/gi, '"')
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}
