// AUTO-GENERATED by `pnpm sync-mcp-runner-version`. DO NOT EDIT BY HAND.
// Mirrors the latest published `@prepsavant/mcp` version so local dev builds
// of the runner can surface a meaningful version without reading
// package.json at runtime (the JSON file isn't copied into `dist` when we
// publish from the standalone public repo).
export const ADAPTER_VERSION = "0.4.0";
